export const TRAINING_PLAN_TEMPLATES = [
  {
    title: "Total Body Transformation",
    description:
      "Modern, science-based plan for full body transformation. Includes strength, HIIT, and mobility sessions. Perfect for busy professionals.",
    coverImage:
      "https://images.pexels.com/photos/2261482/pexels-photo-2261482.jpeg",
    price: 49,
    duration: 6,
    durationType: "weeks",
    keyFeatures: [
      "Personalized schedule",
      "Video instructions",
      "Progress tracking",
      "24/7 chat support",
      "Flexible rescheduling",
    ],
    trainingType: "with_trainer",
    timeline: [
      {
        week: "1",
        title: "Kickoff & Assessment",
        description: "Initial assessment and light full body workouts.",
      },
      {
        week: "2-3",
        title: "Strength Foundation",
        description: "Progressive overload, focus on form and technique.",
      },
      {
        week: "4-5",
        title: "HIIT & Conditioning",
        description: "Add HIIT and mobility for fat loss and flexibility.",
      },
      {
        week: "6",
        title: "Peak Week",
        description: "Test your progress, max out, and get feedback.",
      },
    ],
    features: {
      onlineCalls: true,
      support24_7: true,
      liveTraining: true,
      mealPlanning: true,
      recoveryPlans: true,
      progressTracking: true,
      flexibleScheduling: true,
      personalizedNutrition: true,
    },
    sessionsPerWeek: 4,
    sessionFormat: { inPerson: true, online: false },
    difficultyLevel: "beginner",
    schedule: [
      {
        day: 1,
        name: "Full Body Strength",
        type: "strength",
        duration: 60,
        exercises: [
          {
            name: "Barbell Squat",
            reps: 10,
            rest: 60,
            sets: 3,
            type: "strength",
            level: "beginner",
            imageUrl:
              "https://images.pexels.com/photos/2261482/pexels-photo-2261482.jpeg",
            location: "gym",
            equipment: true,
            instructions:
              "Stand with feet shoulder-width apart, squat down, keep back straight, return up.",
            muscleGroups: [
              { name: "quadriceps" },
              { name: "glutes" },
              { name: "core" },
            ],
          },
          {
            name: "Push-ups",
            reps: 15,
            rest: 45,
            sets: 3,
            type: "bodyweight",
            level: "beginner",
            imageUrl:
              "https://images.pexels.com/photos/416778/pexels-photo-416778.jpeg",
            location: "home",
            equipment: false,
            instructions:
              "Start in plank, lower chest to floor, push back up, keep core tight.",
            muscleGroups: [
              { name: "chest" },
              { name: "shoulders" },
              { name: "triceps" },
            ],
          },
        ],
        description: "Focus on compound movements.",
      },
      {
        day: 3,
        name: "HIIT & Core",
        type: "hiit",
        duration: 45,
        exercises: [
          {
            name: "Burpees",
            reps: 12,
            rest: 30,
            sets: 4,
            type: "hiit",
            level: "beginner",
            imageUrl:
              "https://images.pexels.com/photos/1552242/pexels-photo-1552242.jpeg",
            location: "home",
            equipment: false,
            instructions:
              "Squat, jump to plank, push-up, jump back, stand and jump.",
            muscleGroups: [{ name: "full body" }],
          },
          {
            name: "Plank",
            reps: 1,
            rest: 30,
            sets: 3,
            type: "core",
            level: "beginner",
            imageUrl:
              "https://images.pexels.com/photos/4056723/pexels-photo-4056723.jpeg",
            location: "home",
            equipment: false,
            instructions: "Hold plank position for 45 seconds.",
            muscleGroups: [{ name: "core" }, { name: "shoulders" }],
          },
        ],
        description: "HIIT intervals and core stability.",
      },
      {
        day: 5,
        name: "Mobility & Recovery",
        type: "mobility",
        duration: 40,
        exercises: [
          {
            name: "Dynamic Stretching",
            reps: 1,
            rest: 0,
            sets: 1,
            type: "mobility",
            level: "beginner",
            imageUrl:
              "https://images.pexels.com/photos/3757957/pexels-photo-3757957.jpeg",
            location: "home",
            equipment: false,
            instructions:
              "Perform dynamic stretches for all major muscle groups.",
            muscleGroups: [{ name: "full body" }],
          },
        ],
        description: "Mobility, stretching, and active recovery.",
      },
    ],
  },
  {
    title: "Fat Loss HIIT Blast",
    description:
      "High-intensity interval training focused on rapid fat loss and cardiovascular health. Minimal equipment, maximum sweat.",
    coverImage:
      "https://images.pexels.com/photos/1552242/pexels-photo-1552242.jpeg",
    price: 39,
    duration: 4,
    durationType: "weeks",
    keyFeatures: [
      "HIIT intervals",
      "Bodyweight only",
      "Fat burning focus",
      "Quick 30-40 min sessions",
      "No gym required",
    ],
    trainingType: "with_trainer",
    timeline: [
      {
        week: "1",
        title: "HIIT Foundations",
        description: "Learn proper form and interval basics.",
      },
      {
        week: "2",
        title: "Intensity Ramp Up",
        description: "Increase work intervals, reduce rest.",
      },
      {
        week: "3",
        title: "Metabolic Burn",
        description: "Add compound moves and circuits.",
      },
      {
        week: "4",
        title: "Final Push",
        description: "Challenge week, test your limits!",
      },
    ],
    features: {
      onlineCalls: false,
      support24_7: true,
      liveTraining: false,
      mealPlanning: true,
      recoveryPlans: true,
      progressTracking: true,
      flexibleScheduling: true,
      personalizedNutrition: false,
    },
    sessionsPerWeek: 5,
    sessionFormat: { inPerson: false, online: true },
    difficultyLevel: "intermediate",
    schedule: [
      {
        day: 1,
        name: "Full Body HIIT",
        type: "hiit",
        duration: 35,
        exercises: [
          {
            name: "Jump Squats",
            reps: 15,
            rest: 20,
            sets: 4,
            type: "hiit",
            level: "intermediate",
            imageUrl:
              "https://images.pexels.com/photos/1552242/pexels-photo-1552242.jpeg",
            location: "home",
            equipment: false,
            instructions: "Explode up, land softly, keep core tight.",
            muscleGroups: [{ name: "legs" }, { name: "glutes" }],
          },
          {
            name: "Mountain Climbers",
            reps: 30,
            rest: 20,
            sets: 4,
            type: "hiit",
            level: "intermediate",
            imageUrl:
              "https://images.pexels.com/photos/1552242/pexels-photo-1552242.jpeg",
            location: "home",
            equipment: false,
            instructions: "Drive knees to chest quickly, keep hips low.",
            muscleGroups: [{ name: "core" }, { name: "shoulders" }],
          },
        ],
        description: "Classic HIIT circuit.",
      },
      {
        day: 3,
        name: "Core & Cardio",
        type: "hiit",
        duration: 30,
        exercises: [
          {
            name: "High Knees",
            reps: 40,
            rest: 20,
            sets: 4,
            type: "hiit",
            level: "intermediate",
            imageUrl:
              "https://images.pexels.com/photos/1552242/pexels-photo-1552242.jpeg",
            location: "home",
            equipment: false,
            instructions: "Run in place, knees above hips.",
            muscleGroups: [{ name: "legs" }, { name: "core" }],
          },
          {
            name: "Russian Twists",
            reps: 20,
            rest: 20,
            sets: 4,
            type: "core",
            level: "intermediate",
            imageUrl:
              "https://images.pexels.com/photos/4056723/pexels-photo-4056723.jpeg",
            location: "home",
            equipment: false,
            instructions: "Twist torso side to side, keep feet off ground.",
            muscleGroups: [{ name: "core" }],
          },
        ],
        description: "Core and cardio blast.",
      },
      {
        day: 5,
        name: "Tabata Burnout",
        type: "hiit",
        duration: 30,
        exercises: [
          {
            name: "Burpees",
            reps: 10,
            rest: 10,
            sets: 8,
            type: "hiit",
            level: "intermediate",
            imageUrl:
              "https://images.pexels.com/photos/1552242/pexels-photo-1552242.jpeg",
            location: "home",
            equipment: false,
            instructions:
              "Classic burpee, as many reps as possible in interval.",
            muscleGroups: [{ name: "full body" }],
          },
        ],
        description: "Tabata protocol for max burn.",
      },
    ],
  },
  {
    title: "Muscle Gain Pro",
    description:
      "Progressive hypertrophy program for building muscle mass. Gym-based, science-backed, and periodized for results.",
    coverImage:
      "https://images.pexels.com/photos/2261482/pexels-photo-2261482.jpeg",
    price: 59,
    duration: 8,
    durationType: "weeks",
    keyFeatures: [
      "Progressive overload",
      "Upper/lower split",
      "Strength & hypertrophy",
      "Nutrition guidance",
      "Weekly check-ins",
    ],
    trainingType: "with_trainer",
    timeline: [
      {
        week: "1-2",
        title: "Base Building",
        description: "Establish technique and volume base.",
      },
      {
        week: "3-5",
        title: "Volume Phase",
        description: "Increase sets and reps for hypertrophy.",
      },
      {
        week: "6-7",
        title: "Intensity Phase",
        description: "Lift heavier, lower reps.",
      },
      {
        week: "8",
        title: "Deload & Test",
        description: "Reduce volume, test new maxes.",
      },
    ],
    features: {
      onlineCalls: true,
      support24_7: false,
      liveTraining: true,
      mealPlanning: true,
      recoveryPlans: true,
      progressTracking: true,
      flexibleScheduling: false,
      personalizedNutrition: true,
    },
    sessionsPerWeek: 5,
    sessionFormat: { inPerson: true, online: false },
    difficultyLevel: "intermediate",
    schedule: [
      {
        day: 1,
        name: "Upper Body Strength",
        type: "strength",
        duration: 70,
        exercises: [
          {
            name: "Bench Press",
            reps: 8,
            rest: 90,
            sets: 4,
            type: "strength",
            level: "intermediate",
            imageUrl:
              "https://images.pexels.com/photos/2261482/pexels-photo-2261482.jpeg",
            location: "gym",
            equipment: true,
            instructions: "Lower bar to chest, press up, keep feet flat.",
            muscleGroups: [
              { name: "chest" },
              { name: "triceps" },
              { name: "shoulders" },
            ],
          },
          {
            name: "Pull-ups",
            reps: 8,
            rest: 90,
            sets: 4,
            type: "bodyweight",
            level: "intermediate",
            imageUrl:
              "https://images.pexels.com/photos/416778/pexels-photo-416778.jpeg",
            location: "gym",
            equipment: true,
            instructions: "Full hang, chin over bar, control down.",
            muscleGroups: [{ name: "back" }, { name: "biceps" }],
          },
        ],
        description: "Compound upper body focus.",
      },
      {
        day: 3,
        name: "Lower Body Hypertrophy",
        type: "strength",
        duration: 70,
        exercises: [
          {
            name: "Barbell Squat",
            reps: 10,
            rest: 90,
            sets: 4,
            type: "strength",
            level: "intermediate",
            imageUrl:
              "https://images.pexels.com/photos/2261482/pexels-photo-2261482.jpeg",
            location: "gym",
            equipment: true,
            instructions: "Squat to parallel, drive up through heels.",
            muscleGroups: [
              { name: "quadriceps" },
              { name: "glutes" },
              { name: "core" },
            ],
          },
          {
            name: "Romanian Deadlift",
            reps: 10,
            rest: 90,
            sets: 4,
            type: "strength",
            level: "intermediate",
            imageUrl:
              "https://images.pexels.com/photos/2261482/pexels-photo-2261482.jpeg",
            location: "gym",
            equipment: true,
            instructions: "Hinge at hips, keep back flat, stretch hamstrings.",
            muscleGroups: [{ name: "hamstrings" }, { name: "glutes" }],
          },
        ],
        description: "Legs and posterior chain.",
      },
      {
        day: 5,
        name: "Push & Pull",
        type: "strength",
        duration: 60,
        exercises: [
          {
            name: "Overhead Press",
            reps: 8,
            rest: 90,
            sets: 4,
            type: "strength",
            level: "intermediate",
            imageUrl:
              "https://images.pexels.com/photos/2261482/pexels-photo-2261482.jpeg",
            location: "gym",
            equipment: true,
            instructions: "Press bar overhead, lock out elbows.",
            muscleGroups: [{ name: "shoulders" }, { name: "triceps" }],
          },
          {
            name: "Barbell Row",
            reps: 10,
            rest: 90,
            sets: 4,
            type: "strength",
            level: "intermediate",
            imageUrl:
              "https://images.pexels.com/photos/2261482/pexels-photo-2261482.jpeg",
            location: "gym",
            equipment: true,
            instructions: "Pull bar to lower chest, squeeze shoulder blades.",
            muscleGroups: [{ name: "back" }, { name: "biceps" }],
          },
        ],
        description: "Push and pull compound lifts.",
      },
    ],
  },
  {
    title: "Powerlifting Prep",
    description:
      "Strength-focused program for squat, bench, and deadlift. Ideal for those prepping for their first meet or wanting to get strong.",
    coverImage:
      "https://images.pexels.com/photos/2261482/pexels-photo-2261482.jpeg",
    price: 69,
    duration: 10,
    durationType: "weeks",
    keyFeatures: [
      "Squat, bench, deadlift",
      "Linear progression",
      "Technique focus",
      "Peaking phase",
      "Meet day strategy",
    ],
    trainingType: "with_trainer",
    timeline: [
      {
        week: "1-4",
        title: "Base Strength",
        description: "Build base with moderate volume.",
      },
      {
        week: "5-7",
        title: "Intensity Increase",
        description: "Increase weights, reduce reps.",
      },
      {
        week: "8-9",
        title: "Peaking",
        description: "Low volume, high intensity.",
      },
      { week: "10", title: "Meet Week", description: "Taper and test maxes." },
    ],
    features: {
      onlineCalls: true,
      support24_7: false,
      liveTraining: true,
      mealPlanning: false,
      recoveryPlans: true,
      progressTracking: true,
      flexibleScheduling: false,
      personalizedNutrition: false,
    },
    sessionsPerWeek: 4,
    sessionFormat: { inPerson: true, online: false },
    difficultyLevel: "advanced",
    schedule: [
      {
        day: 1,
        name: "Squat Focus",
        type: "strength",
        duration: 80,
        exercises: [
          {
            name: "Back Squat",
            reps: 5,
            rest: 180,
            sets: 5,
            type: "strength",
            level: "advanced",
            imageUrl:
              "https://images.pexels.com/photos/2261482/pexels-photo-2261482.jpeg",
            location: "gym",
            equipment: true,
            instructions: "Squat deep, keep chest up, drive through heels.",
            muscleGroups: [
              { name: "quadriceps" },
              { name: "glutes" },
              { name: "core" },
            ],
          },
          {
            name: "Paused Squat",
            reps: 3,
            rest: 120,
            sets: 3,
            type: "strength",
            level: "advanced",
            imageUrl:
              "https://images.pexels.com/photos/2261482/pexels-photo-2261482.jpeg",
            location: "gym",
            equipment: true,
            instructions: "Pause at bottom for 2s, then drive up.",
            muscleGroups: [{ name: "quadriceps" }, { name: "glutes" }],
          },
        ],
        description: "Squat technique and strength.",
      },
      {
        day: 3,
        name: "Bench Press Focus",
        type: "strength",
        duration: 70,
        exercises: [
          {
            name: "Bench Press",
            reps: 5,
            rest: 180,
            sets: 5,
            type: "strength",
            level: "advanced",
            imageUrl:
              "https://images.pexels.com/photos/2261482/pexels-photo-2261482.jpeg",
            location: "gym",
            equipment: true,
            instructions: "Lower bar to chest, press up, keep feet flat.",
            muscleGroups: [
              { name: "chest" },
              { name: "triceps" },
              { name: "shoulders" },
            ],
          },
          {
            name: "Close Grip Bench",
            reps: 6,
            rest: 120,
            sets: 3,
            type: "strength",
            level: "advanced",
            imageUrl:
              "https://images.pexels.com/photos/2261482/pexels-photo-2261482.jpeg",
            location: "gym",
            equipment: true,
            instructions: "Hands shoulder-width, focus on triceps.",
            muscleGroups: [{ name: "triceps" }, { name: "chest" }],
          },
        ],
        description: "Bench press and triceps.",
      },
      {
        day: 5,
        name: "Deadlift Focus",
        type: "strength",
        duration: 80,
        exercises: [
          {
            name: "Deadlift",
            reps: 5,
            rest: 180,
            sets: 5,
            type: "strength",
            level: "advanced",
            imageUrl:
              "https://images.pexels.com/photos/2261482/pexels-photo-2261482.jpeg",
            location: "gym",
            equipment: true,
            instructions: "Pull from floor, lock out at top, control down.",
            muscleGroups: [
              { name: "back" },
              { name: "glutes" },
              { name: "hamstrings" },
            ],
          },
          {
            name: "Romanian Deadlift",
            reps: 8,
            rest: 120,
            sets: 3,
            type: "strength",
            level: "advanced",
            imageUrl:
              "https://images.pexels.com/photos/2261482/pexels-photo-2261482.jpeg",
            location: "gym",
            equipment: true,
            instructions: "Hinge at hips, stretch hamstrings.",
            muscleGroups: [{ name: "hamstrings" }, { name: "glutes" }],
          },
        ],
        description: "Deadlift and posterior chain.",
      },
    ],
  },
  {
    title: "Mobility & Flexibility",
    description:
      "A gentle program to improve mobility, flexibility, and joint health. Great for all levels and as active recovery.",
    coverImage:
      "https://images.pexels.com/photos/3757957/pexels-photo-3757957.jpeg",
    price: 29,
    duration: 3,
    durationType: "weeks",
    keyFeatures: [
      "Daily mobility routines",
      "Stretching guidance",
      "Joint health focus",
      "No equipment needed",
      "Active recovery",
    ],
    trainingType: "with_trainer",
    timeline: [
      {
        week: "1",
        title: "Mobility Basics",
        description: "Learn and practice daily mobility drills.",
      },
      {
        week: "2",
        title: "Flexibility Progression",
        description: "Increase range of motion and hold times.",
      },
      {
        week: "3",
        title: "Integration",
        description: "Combine mobility and flexibility for full body flow.",
      },
    ],
    features: {
      onlineCalls: false,
      support24_7: true,
      liveTraining: false,
      mealPlanning: false,
      recoveryPlans: true,
      progressTracking: false,
      flexibleScheduling: true,
      personalizedNutrition: false,
    },
    sessionsPerWeek: 6,
    sessionFormat: { inPerson: false, online: true },
    difficultyLevel: "beginner",
    schedule: [
      {
        day: 1,
        name: "Full Body Mobility",
        type: "mobility",
        duration: 30,
        exercises: [
          {
            name: "World's Greatest Stretch",
            reps: 8,
            rest: 30,
            sets: 2,
            type: "mobility",
            level: "beginner",
            imageUrl:
              "https://images.pexels.com/photos/3757957/pexels-photo-3757957.jpeg",
            location: "home",
            equipment: false,
            instructions: "Lunge, twist, reach, repeat both sides.",
            muscleGroups: [{ name: "full body" }],
          },
          {
            name: "Cat-Cow",
            reps: 10,
            rest: 15,
            sets: 2,
            type: "mobility",
            level: "beginner",
            imageUrl:
              "https://images.pexels.com/photos/3757957/pexels-photo-3757957.jpeg",
            location: "home",
            equipment: false,
            instructions: "Alternate arching and rounding back.",
            muscleGroups: [{ name: "back" }, { name: "core" }],
          },
        ],
        description: "Gentle full body mobility.",
      },
      {
        day: 3,
        name: "Lower Body Flexibility",
        type: "mobility",
        duration: 30,
        exercises: [
          {
            name: "Hamstring Stretch",
            reps: 1,
            rest: 0,
            sets: 2,
            type: "mobility",
            level: "beginner",
            imageUrl:
              "https://images.pexels.com/photos/3757957/pexels-photo-3757957.jpeg",
            location: "home",
            equipment: false,
            instructions: "Hold stretch for 60s per leg.",
            muscleGroups: [{ name: "hamstrings" }],
          },
          {
            name: "Hip Flexor Stretch",
            reps: 1,
            rest: 0,
            sets: 2,
            type: "mobility",
            level: "beginner",
            imageUrl:
              "https://images.pexels.com/photos/3757957/pexels-photo-3757957.jpeg",
            location: "home",
            equipment: false,
            instructions: "Hold stretch for 60s per side.",
            muscleGroups: [{ name: "hip flexors" }],
          },
        ],
        description: "Lower body flexibility.",
      },
      {
        day: 5,
        name: "Upper Body Flexibility",
        type: "mobility",
        duration: 30,
        exercises: [
          {
            name: "Shoulder Stretch",
            reps: 1,
            rest: 0,
            sets: 2,
            type: "mobility",
            level: "beginner",
            imageUrl:
              "https://images.pexels.com/photos/3757957/pexels-photo-3757957.jpeg",
            location: "home",
            equipment: false,
            instructions: "Hold stretch for 60s per arm.",
            muscleGroups: [{ name: "shoulders" }],
          },
          {
            name: "Triceps Stretch",
            reps: 1,
            rest: 0,
            sets: 2,
            type: "mobility",
            level: "beginner",
            imageUrl:
              "https://images.pexels.com/photos/3757957/pexels-photo-3757957.jpeg",
            location: "home",
            equipment: false,
            instructions: "Hold stretch for 60s per arm.",
            muscleGroups: [{ name: "triceps" }],
          },
        ],
        description: "Upper body flexibility.",
      },
    ],
  },
  {
    title: "Home Workout Essentials",
    description:
      "No equipment? No problem! This plan uses only bodyweight and is perfect for training at home or while traveling.",
    coverImage:
      "https://images.pexels.com/photos/416778/pexels-photo-416778.jpeg",
    price: 19,
    duration: 4,
    durationType: "weeks",
    keyFeatures: [
      "Bodyweight only",
      "Minimal space needed",
      "Quick sessions",
      "All levels welcome",
      "No gym required",
    ],
    trainingType: "with_trainer",
    timeline: [
      {
        week: "1",
        title: "Getting Started",
        description: "Learn the basics and set a routine.",
      },
      {
        week: "2",
        title: "Progression",
        description: "Increase reps and sets, add new moves.",
      },
      {
        week: "3",
        title: "Challenge Week",
        description: "Try new variations and circuits.",
      },
      {
        week: "4",
        title: "Mastery",
        description: "Combine all skills for full body challenge.",
      },
    ],
    features: {
      onlineCalls: false,
      support24_7: true,
      liveTraining: false,
      mealPlanning: false,
      recoveryPlans: true,
      progressTracking: true,
      flexibleScheduling: true,
      personalizedNutrition: false,
    },
    sessionsPerWeek: 4,
    sessionFormat: { inPerson: false, online: true },
    difficultyLevel: "beginner",
    schedule: [
      {
        day: 1,
        name: "Upper Body Bodyweight",
        type: "bodyweight",
        duration: 35,
        exercises: [
          {
            name: "Push-ups",
            reps: 15,
            rest: 45,
            sets: 3,
            type: "bodyweight",
            level: "beginner",
            imageUrl:
              "https://images.pexels.com/photos/416778/pexels-photo-416778.jpeg",
            location: "home",
            equipment: false,
            instructions: "Standard push-up, keep core tight.",
            muscleGroups: [
              { name: "chest" },
              { name: "shoulders" },
              { name: "triceps" },
            ],
          },
          {
            name: "Triceps Dips",
            reps: 12,
            rest: 45,
            sets: 3,
            type: "bodyweight",
            level: "beginner",
            imageUrl:
              "https://images.pexels.com/photos/416778/pexels-photo-416778.jpeg",
            location: "home",
            equipment: false,
            instructions: "Use chair or low table, lower and press up.",
            muscleGroups: [{ name: "triceps" }, { name: "shoulders" }],
          },
        ],
        description: "Upper body at home.",
      },
      {
        day: 3,
        name: "Lower Body Bodyweight",
        type: "bodyweight",
        duration: 35,
        exercises: [
          {
            name: "Bodyweight Squats",
            reps: 20,
            rest: 45,
            sets: 3,
            type: "bodyweight",
            level: "beginner",
            imageUrl:
              "https://images.pexels.com/photos/416778/pexels-photo-416778.jpeg",
            location: "home",
            equipment: false,
            instructions: "Squat down, keep chest up, drive through heels.",
            muscleGroups: [{ name: "quadriceps" }, { name: "glutes" }],
          },
          {
            name: "Lunges",
            reps: 12,
            rest: 45,
            sets: 3,
            type: "bodyweight",
            level: "beginner",
            imageUrl:
              "https://images.pexels.com/photos/416778/pexels-photo-416778.jpeg",
            location: "home",
            equipment: false,
            instructions: "Step forward, lower knee, alternate legs.",
            muscleGroups: [{ name: "quadriceps" }, { name: "glutes" }],
          },
        ],
        description: "Lower body at home.",
      },
      {
        day: 5,
        name: "Core & Cardio",
        type: "bodyweight",
        duration: 30,
        exercises: [
          {
            name: "Plank",
            reps: 1,
            rest: 30,
            sets: 3,
            type: "core",
            level: "beginner",
            imageUrl:
              "https://images.pexels.com/photos/4056723/pexels-photo-4056723.jpeg",
            location: "home",
            equipment: false,
            instructions: "Hold plank for 45 seconds.",
            muscleGroups: [{ name: "core" }],
          },
          {
            name: "Jumping Jacks",
            reps: 30,
            rest: 30,
            sets: 3,
            type: "cardio",
            level: "beginner",
            imageUrl:
              "https://images.pexels.com/photos/416778/pexels-photo-416778.jpeg",
            location: "home",
            equipment: false,
            instructions: "Jump feet out, arms overhead, repeat.",
            muscleGroups: [{ name: "full body" }],
          },
        ],
        description: "Core and cardio at home.",
      },
    ],
  },
];
