export const TRAINING_FEATURE_OPTIONS = [
  {
    key: "support24_7",
    label: "24/7 Support & Consultation",
    icon: "mdi:clock-time-four-outline",
    description: "Round-the-clock support for your clients",
    color: "from-blue-500/20 to-indigo-500/20 border-indigo-500/30",
    iconColor: "text-indigo-400",
  },
  {
    key: "liveTraining",
    label: "Live Training Sessions",
    icon: "mdi:dumbbell",
    description: "Real-time workout sessions with clients",
    color: "from-orange-500/20 to-red-500/20 border-red-500/30",
    iconColor: "text-red-400",
  },
  {
    key: "onlineCalls",
    label: "Online Video Calls",
    icon: "mdi:video-outline",
    description: "Virtual consultations and check-ins",
    color: "from-green-500/20 to-emerald-500/20 border-emerald-500/30",
    iconColor: "text-emerald-400",
  },
  {
    key: "personalizedNutrition",
    label: "Personalized Nutrition Plan",
    icon: "mdi:nutrition",
    description: "Custom diet plans for each client",
    color: "from-purple-500/20 to-violet-500/20 border-violet-500/30",
    iconColor: "text-violet-400",
  },
  {
    key: "progressTracking",
    label: "Progress Tracking",
    icon: "mdi:chart-line",
    description: "Detailed progress monitoring and analytics",
    color: "from-cyan-500/20 to-blue-500/20 border-blue-500/30",
    iconColor: "text-cyan-400",
  },
  {
    key: "mealPlanning",
    label: "Weekly Meal Planning",
    icon: "mdi:food-apple-outline",
    description: "Structured meal plans and recipes",
    color: "from-green-500/20 to-lime-500/20 border-lime-500/30",
    iconColor: "text-lime-400",
  },
  {
    key: "flexibleScheduling",
    label: "Flexible Scheduling",
    icon: "mdi:calendar-clock",
    description: "Adaptable training schedule",
    color: "from-yellow-500/20 to-amber-500/20 border-amber-500/30",
    iconColor: "text-amber-400",
  },
  {
    key: "recoveryPlans",
    label: "Recovery Plans",
    icon: "mdi:meditation",
    description: "Rest and recovery guidance",
    color: "from-teal-500/20 to-cyan-500/20 border-teal-500/30",
    iconColor: "text-teal-400",
  },
];
