export const SESSION_FORMATS = [
  {
    id: "inPerson",
    label: "In-Person",
    description: "Face-to-face training sessions",
    icon: "mdi:account-group",
    color: "bg-gradient-to-br from-blue-500 to-indigo-600 shadow-xl",
    bgClass: "bg-blue-500/10",
    borderColor: "border-blue-500/30",
    ringClass: "ring-2 ring-blue-500/20",
  },
  {
    id: "online",
    label: "Online",
    description: "Virtual training sessions",
    icon: "mdi:video-outline",
    color: "bg-gradient-to-br from-emerald-500 to-green-600 shadow-xl",
    bgClass: "bg-emerald-500/10",
    borderColor: "border-emerald-500/30",
    ringClass: "ring-2 ring-emerald-500/20",
  },
  {
    id: "hybrid",
    label: "Hybrid",
    description: "Mix of in-person and online",
    icon: "mdi:swap-horizontal",
    color: "bg-gradient-to-br from-violet-500 to-purple-600 shadow-xl",
    bgClass: "bg-violet-500/10",
    borderColor: "border-violet-500/30",
    ringClass: "ring-2 ring-violet-500/20",
  },
  {
    id: "selfGuided",
    label: "Self-Guided",
    description: "Independent workout plans",
    icon: "mdi:clipboard-text-outline",
    color: "bg-gradient-to-br from-[#FF6B00] to-[#FF8533] shadow-xl",
    bgClass: "bg-[#FF6B00]/10",
    borderColor: "border-[#FF6B00]/30",
    ringClass: "ring-2 ring-[#FF6B00]/20",
  },
];
