export const TRAINING_LEVELS = [
  {
    id: "beginner",
    label: "Beginner",
    description: "New to fitness training",
    icon: "mdi:baby-face-outline",
    color: "bg-gradient-to-br from-emerald-500 to-green-600 shadow-xl",
    bgClass: "bg-emerald-500/10",
    borderColor: "border-emerald-500/30",
    ringClass: "ring-2 ring-emerald-500/20",
  },
  {
    id: "intermediate",
    label: "Intermediate",
    description: "Some training experience",
    icon: "mdi:account-outline",
    color: "bg-gradient-to-br from-blue-500 to-indigo-600 shadow-xl",
    bgClass: "bg-blue-500/10",
    borderColor: "border-blue-500/30",
    ringClass: "ring-2 ring-blue-500/20",
  },
  {
    id: "advanced",
    label: "Advanced",
    description: "Experienced athletes",
    icon: "mdi:trophy-outline",
    color: "bg-gradient-to-br from-violet-500 to-purple-600 shadow-xl",
    bgClass: "bg-violet-500/10",
    borderColor: "border-violet-500/30",
    ringClass: "ring-2 ring-violet-500/20",
  },
];
