export const clientPricingPlans = [
    {
        name: "Basic",
        price: "0.00",
        yearlySavings: 0,
        popular: false,
        btnText: "Start for Free",
        description: "Perfect for beginners starting their fitness journey.",
        users: "1 client",
        storage: "250MB",
        support: "Basic",
        features: [
            "Basic workout tracking",
            "Simple progress monitoring",
            "Basic nutrition logging",
            "Limited workout history",
            "Basic health metrics",
        ],
    },
    {
        name: "Pro",
        price: "29.99",
        yearlySavings: 119.88,
        popular: true,
        btnText: "Upgrade to Pro",
        description: "Ideal for serious fitness enthusiasts.",
        users: "1 client",
        storage: "5GB",
        support: "Priority",
        features: [
            "All Basic features",
            "Advanced workout analytics",
            "Detailed progress tracking",
            "Nutrition plan customization",
            "Integration with fitness devices",
        ],
    },
    {
        name: "Elite",
        price: "49.99",
        yearlySavings: 199.96,
        popular: false,
        btnText: "Go Elite",
        description: "For those who want the complete fitness experience.",
        users: "1 client",
        storage: "Unlimited",
        support: "24/7 Premium",
        features: [
            "All Pro features",
            "Personalized AI workout plans",
            "Advanced nutrition analysis",
            "Premium trainer matching",
            "Exclusive fitness content",
        ],
    },
];

export const trainerPricingPlans = [
    {
        name: "Starter",
        price: "49.99",
        yearlySavings: 199.96,
        popular: false,
        btnText: "Start Training",
        description: "Perfect for new trainers building their client base.",
        users: "Up to 10 clients",
        storage: "1GB",
        support: "Basic",
        features: [
            "Client management dashboard",
            "Basic workout planning",
            "Client progress tracking",
            "Simple scheduling system",
            "Basic reporting tools",
        ],
    },
    {
        name: "Professional",
        price: "99.99",
        yearlySavings: 399.96,
        popular: true,
        btnText: "Go Professional",
        description: "For established trainers with growing client base.",
        users: "Up to 50 clients",
        storage: "10GB",
        support: "Priority",
        features: [
            "All Starter features",
            "Advanced client analytics",
            "Custom workout templates",
            "Nutrition planning tools",
            "Client communication portal",
        ],
    },
    {
        name: "Enterprise",
        price: "199.99",
        yearlySavings: 799.96,
        popular: false,
        btnText: "Scale Your Business",
        description: "For successful trainers and fitness businesses.",
        users: "Unlimited clients",
        storage: "Unlimited",
        support: "24/7 Premium",
        features: [
            "All Professional features",
            "Team management tools",
            "Advanced business analytics",
            "Custom branding options",
            "API access for integrations",
        ],
    },
];

export const userPricingPlans = [
    {
        name: "Basic",
        price: "0.00",
        yearlySavings: 0,
        popular: false,
        btnText: "Start Free",
        description: "Essential features for personal fitness tracking.",
        users: "1 user",
        storage: "250MB",
        support: "Basic",
        features: [
            "Basic workout logging",
            "Simple progress tracking",
            "Basic nutrition tracking",
            "Limited workout history",
            "Basic health metrics",
        ],
    },
    {
        name: "Premium",
        price: "19.99",
        yearlySavings: 79.96,
        popular: true,
        btnText: "Go Premium",
        description: "Enhanced features for serious fitness enthusiasts.",
        users: "1 user",
        storage: "5GB",
        support: "Priority",
        features: [
            "All Basic features",
            "Advanced workout analytics",
            "Detailed progress tracking",
            "Custom nutrition plans",
            "Fitness device integration",
        ],
    },
    {
        name: "Ultimate",
        price: "39.99",
        yearlySavings: 159.96,
        popular: false,
        btnText: "Get Ultimate",
        description: "Complete fitness solution with premium features.",
        users: "1 user",
        storage: "Unlimited",
        support: "24/7 Premium",
        features: [
            "All Premium features",
            "AI-powered workout plans",
            "Advanced nutrition analysis",
            "Premium content access",
            "Priority feature requests",
        ],
    },
];
