const countryOptions = [
  {
    flagName: "🇦🇫",
    countryName: "Afghanistan",
    countryWithFlag: "🇦🇫 Afghanistan",
    shortCode: "AF (+93)",
    countryWithCode: "Afghanistan (+93)",
    value: "+93",
    languageName: "🇦🇫 پښتو", // Pashto
  },
  {
    flagName: "🇦🇱",
    countryName: "Albania",
    countryWithFlag: "🇦🇱 Albania",
    shortCode: "AL (+355)",
    countryWithCode: "Albania (+355)",
    value: "+355",
    languageName: "🇦🇱 Shqip",
  },
  {
    flagName: "🇩🇿",
    countryName: "Algeria",
    countryWithFlag: "🇩🇿 Algeria",
    shortCode: "DZ (+213)",
    countryWithCode: "Algeria (+213)",
    value: "+213",
    languageName: "🇩🇿 العربية",
  },
  {
    flagName: "🇦🇸",
    countryName: "American Samoa",
    countryWithFlag: "🇦🇸 American Samoa",
    shortCode: "AS (+1-684)",
    countryWithCode: "American Samoa (+1-684)",
    value: "+1-684",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇦🇩",
    countryName: "Andorra",
    countryWithFlag: "🇦🇩 Andorra",
    shortCode: "AD (+376)",
    countryWithCode: "Andorra (+376)",
    value: "+376",
    languageName: "🇦🇩 Català",
  },
  {
    flagName: "🇦🇴",
    countryName: "Angola",
    countryWithFlag: "🇦🇴 Angola",
    shortCode: "AO (+244)",
    countryWithCode: "Angola (+244)",
    value: "+244",
    languageName: "🇦🇴 Português",
  },
  {
    flagName: "🇦🇮",
    countryName: "Anguilla",
    countryWithFlag: "🇦🇮 Anguilla",
    shortCode: "AI (+1-264)",
    countryWithCode: "Anguilla (+1-264)",
    value: "+1-264",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇦🇶",
    countryName: "Antarctica",
    countryWithFlag: "🇦🇶 Antarctica",
    shortCode: "AQ (+672)",
    countryWithCode: "Antarctica (+672)",
    value: "+672",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇦🇬",
    countryName: "Antigua and Barbuda",
    countryWithFlag: "🇦🇬 Antigua and Barbuda",
    shortCode: "AG (+1-268)",
    countryWithCode: "Antigua and Barbuda (+1-268)",
    value: "+1-268",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇦🇷",
    countryName: "Argentina",
    countryWithFlag: "🇦🇷 Argentina",
    shortCode: "AR (+54)",
    countryWithCode: "Argentina (+54)",
    value: "+54",
    languageName: "🇦🇷 Español",
  },
  {
    flagName: "🇦🇲",
    countryName: "Armenia",
    countryWithFlag: "🇦🇲 Armenia",
    shortCode: "AM (+374)",
    countryWithCode: "Armenia (+374)",
    value: "+374",
    languageName: "🇦🇲 Armenian",
  },
  {
    flagName: "🇦🇼",
    countryName: "Aruba",
    countryWithFlag: "🇦🇼 Aruba",
    shortCode: "AW (+297)",
    countryWithCode: "Aruba (+297)",
    value: "+297",
    languageName: "🇦🇼 Papiamento",
  },
  {
    flagName: "🇦🇺",
    countryName: "Australia",
    countryWithFlag: "🇦🇺 Australia",
    shortCode: "AU (+61)",
    countryWithCode: "Australia (+61)",
    value: "+61",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇦🇹",
    countryName: "Austria",
    countryWithFlag: "🇦🇹 Austria",
    shortCode: "AT (+43)",
    countryWithCode: "Austria (+43)",
    value: "+43",
    languageName: "🇦🇹 Deutsch",
  },
  {
    flagName: "🇦🇿",
    countryName: "Azerbaijan",
    countryWithFlag: "🇦🇿 Azerbaijan",
    shortCode: "AZ (+994)",
    countryWithCode: "Azerbaijan (+994)",
    value: "+994",
    languageName: "🇦🇿 Azərbaycan",
  },
  {
    flagName: "🇧🇸",
    countryName: "Bahamas",
    countryWithFlag: "🇧🇸 Bahamas",
    shortCode: "BS (+1-242)",
    countryWithCode: "Bahamas (+1-242)",
    value: "+1-242",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇧🇭",
    countryName: "Bahrain",
    countryWithFlag: "🇧🇭 Bahrain",
    shortCode: "BH (+973)",
    countryWithCode: "Bahrain (+973)",
    value: "+973",
    languageName: "🇧🇭 العربية",
  },
  {
    flagName: "🇧🇩",
    countryName: "Bangladesh",
    countryWithFlag: "🇧🇩 Bangladesh",
    shortCode: "BD (+880)",
    countryWithCode: "Bangladesh (+880)",
    value: "+880",
    languageName: "🇧🇩 বাংলা",
  },
  {
    flagName: "🇧🇧",
    countryName: "Barbados",
    countryWithFlag: "🇧🇧 Barbados",
    shortCode: "BB (+1-246)",
    countryWithCode: "Barbados (+1-246)",
    value: "+1-246",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇧🇾",
    countryName: "Belarus",
    countryWithFlag: "🇧🇾 Belarus",
    shortCode: "BY (+375)",
    countryWithCode: "Belarus (+375)",
    value: "+375",
    languageName: "🇧🇾 Беларуская",
  },
  {
    flagName: "🇧🇪",
    countryName: "Belgium",
    countryWithFlag: "🇧🇪 Belgium",
    shortCode: "BE (+32)",
    countryWithCode: "Belgium (+32)",
    value: "+32",
    languageName: "🇧🇪 Nederlands",
  },
  {
    flagName: "🇧🇿",
    countryName: "Belize",
    countryWithFlag: "🇧🇿 Belize",
    shortCode: "BZ (+501)",
    countryWithCode: "Belize (+501)",
    value: "+501",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇧🇯",
    countryName: "Benin",
    countryWithFlag: "🇧🇯 Benin",
    shortCode: "BJ (+229)",
    countryWithCode: "Benin (+229)",
    value: "+229",
    languageName: "🇧🇯 Français",
  },
  {
    flagName: "🇧🇲",
    countryName: "Bermuda",
    countryWithFlag: "🇧🇲 Bermuda",
    shortCode: "BM (+1-441)",
    countryWithCode: "Bermuda (+1-441)",
    value: "+1-441",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇧🇹",
    countryName: "Bhutan",
    countryWithFlag: "🇧🇹 Bhutan",
    shortCode: "BT (+975)",
    countryWithCode: "Bhutan (+975)",
    value: "+975",
    languageName: "🇧🇹 Dzongkha",
  },
  {
    flagName: "🇧🇴",
    countryName: "Bolivia",
    countryWithFlag: "🇧🇴 Bolivia",
    shortCode: "BO (+591)",
    countryWithCode: "Bolivia (+591)",
    value: "+591",
    languageName: "🇧🇴 Español",
  },
  {
    flagName: "🇧🇦",
    countryName: "Bosnia and Herzegovina",
    countryWithFlag: "🇧🇦 Bosnia and Herzegovina",
    shortCode: "BA (+387)",
    countryWithCode: "Bosnia and Herzegovina (+387)",
    value: "+387",
    languageName: "🇧🇦 Bosanski",
  },
  {
    flagName: "🇧🇼",
    countryName: "Botswana",
    countryWithFlag: "🇧🇼 Botswana",
    shortCode: "BW (+267)",
    countryWithCode: "Botswana (+267)",
    value: "+267",
    languageName: "🇧🇼 Tswana",
  },
  {
    flagName: "🇧🇷",
    countryName: "Brazil",
    countryWithFlag: "🇧🇷 Brazil",
    shortCode: "BR (+55)",
    countryWithCode: "Brazil (+55)",
    value: "+55",
    languageName: "🇧🇷 Português",
  },
  {
    flagName: "🇮🇴",
    countryName: "British Indian Ocean Territory",
    countryWithFlag: "🇮🇴 British Indian Ocean Territory",
    shortCode: "IO (+246)",
    countryWithCode: "British Indian Ocean Territory (+246)",
    value: "+246",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇻🇬",
    countryName: "British Virgin Islands",
    countryWithFlag: "🇻🇬 British Virgin Islands",
    shortCode: "VG (+1-284)",
    countryWithCode: "British Virgin Islands (+1-284)",
    value: "+1-284",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇧🇳",
    countryName: "Brunei",
    countryWithFlag: "🇧🇳 Brunei",
    shortCode: "BN (+673)",
    countryWithCode: "Brunei (+673)",
    value: "+673",
    languageName: "🇧🇳 Dzongkha",
  },
  {
    flagName: "🇧🇬",
    countryName: "Bulgaria",
    countryWithFlag: "🇧🇬 Bulgaria",
    shortCode: "BG (+359)",
    countryWithCode: "Bulgaria (+359)",
    value: "+359",
    languageName: "🇧🇬 Български",
  },
  {
    flagName: "🇧🇫",
    countryName: "Burkina Faso",
    countryWithFlag: "🇧🇫 Burkina Faso",
    shortCode: "BF (+226)",
    countryWithCode: "Burkina Faso (+226)",
    value: "+226",
    languageName: "🇧🇫 Français",
  },
  {
    flagName: "🇧🇮",
    countryName: "Burundi",
    countryWithFlag: "🇧🇮 Burundi",
    shortCode: "BI (+257)",
    countryWithCode: "Burundi (+257)",
    value: "+257",
    languageName: "🇧🇮 Français",
  },
  {
    flagName: "🇰🇭",
    countryName: "Cambodia",
    countryWithFlag: "🇰🇭 Cambodia",
    shortCode: "KH (+855)",
    countryWithCode: "Cambodia (+855)",
    value: "+855",
    languageName: "🇰🇭 ភាសាខ្មែរ",
  },
  {
    flagName: "🇨🇲",
    countryName: "Cameroon",
    countryWithFlag: "🇨🇲 Cameroon",
    shortCode: "CM (+237)",
    countryWithCode: "Cameroon (+237)",
    value: "+237",
    languageName: "🇨🇲 Français",
  },
  {
    flagName: "🇨🇦",
    countryName: "Canada",
    countryWithFlag: "🇨🇦 Canada",
    shortCode: "CA (+1)",
    countryWithCode: "Canada (+1)",
    value: "+1",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇨🇻",
    countryName: "Cape Verde",
    countryWithFlag: "🇨🇻 Cape Verde",
    shortCode: "CV (+238)",
    countryWithCode: "Cape Verde (+238)",
    value: "+238",
    languageName: "🇨🇻 Português",
  },
  {
    flagName: "🇰🇾",
    countryName: "Cayman Islands",
    countryWithFlag: "🇰🇾 Cayman Islands",
    shortCode: "KY (+1-345)",
    countryWithCode: "Cayman Islands (+1-345)",
    value: "+1-345",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇨🇫",
    countryName: "Central African Republic",
    countryWithFlag: "🇨🇫 Central African Republic",
    shortCode: "CF (+236)",
    countryWithCode: "Central African Republic (+236)",
    value: "+236",
    languageName: "🇨🇫 Français",
  },
  {
    flagName: "🇹🇩",
    countryName: "Chad",
    countryWithFlag: "🇹🇩 Chad",
    shortCode: "TD (+235)",
    countryWithCode: "Chad (+235)",
    value: "+235",
    languageName: "🇹🇩 Français",
  },
  {
    flagName: "🇨🇱",
    countryName: "Chile",
    countryWithFlag: "🇨🇱 Chile",
    shortCode: "CL (+56)",
    countryWithCode: "Chile (+56)",
    value: "+56",
    languageName: "🇨🇱 Español",
  },
  {
    flagName: "🇨🇳",
    countryName: "China",
    countryWithFlag: "🇨🇳 China",
    shortCode: "CN (+86)",
    countryWithCode: "China (+86)",
    value: "+86",
    languageName: "🇨🇳 中文",
  },
  {
    flagName: "🇨🇽",
    countryName: "Christmas Island",
    countryWithFlag: "🇨🇽 Christmas Island",
    shortCode: "CX (+61)",
    countryWithCode: "Christmas Island (+61)",
    value: "+61",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇨🇨",
    countryName: "Cocos Islands",
    countryWithFlag: "🇨🇨 Cocos Islands",
    shortCode: "CC (+61)",
    countryWithCode: "Cocos Islands (+61)",
    value: "+61",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇨🇴",
    countryName: "Colombia",
    countryWithFlag: "🇨🇴 Colombia",
    shortCode: "CO (+57)",
    countryWithCode: "Colombia (+57)",
    value: "+57",
    languageName: "🇨🇴 Español",
  },
  {
    flagName: "🇰🇲",
    countryName: "Comoros",
    countryWithFlag: "🇰🇲 Comoros",
    shortCode: "KM (+269)",
    countryWithCode: "Comoros (+269)",
    value: "+269",
    languageName: "🇰🇲 Français",
  },
  {
    flagName: "🇨🇰",
    countryName: "Cook Islands",
    countryWithFlag: "🇨🇰 Cook Islands",
    shortCode: "CK (+682)",
    countryWithCode: "Cook Islands (+682)",
    value: "+682",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇨🇷",
    countryName: "Costa Rica",
    countryWithFlag: "🇨🇷 Costa Rica",
    shortCode: "CR (+506)",
    countryWithCode: "Costa Rica (+506)",
    value: "+506",
    languageName: "🇨🇷 Español",
  },
  {
    flagName: "🇭🇷",
    countryName: "Croatia",
    countryWithFlag: "🇭🇷 Croatia",
    shortCode: "HR (+385)",
    countryWithCode: "Croatia (+385)",
    value: "+385",
    languageName: "🇭🇷 Hrvatski",
  },
  {
    flagName: "🇨🇺",
    countryName: "Cuba",
    countryWithFlag: "🇨🇺 Cuba",
    shortCode: "CU (+53)",
    countryWithCode: "Cuba (+53)",
    value: "+53",
    languageName: "🇨🇺 Español",
  },
  {
    flagName: "🇨🇼",
    countryName: "Curacao",
    countryWithFlag: "🇨🇼 Curacao",
    shortCode: "CW (+599)",
    countryWithCode: "Curacao (+599)",
    value: "+599",
    languageName: "🇨🇼 Papiamento",
  },
  {
    flagName: "🇨🇾",
    countryName: "Cyprus",
    countryWithFlag: "🇨🇾 Cyprus",
    shortCode: "CY (+357)",
    countryWithCode: "Cyprus (+357)",
    value: "+357",
    languageName: "🇨🇾 Ελληνικά",
  },
  {
    flagName: "🇨🇿",
    countryName: "Czech Republic",
    countryWithFlag: "🇨🇿 Czech Republic",
    shortCode: "CZ (+420)",
    countryWithCode: "Czech Republic (+420)",
    value: "+420",
    languageName: "🇨🇿 Čeština",
  },
  {
    flagName: "🇨🇩",
    countryName: "DR Congo",
    countryWithFlag: "🇨🇩 DR Congo",
    shortCode: "CD (+243)",
    countryWithCode: "DR Congo (+243)",
    value: "+243",
    languageName: "🇨🇩 Français",
  },
  {
    flagName: "🇩🇰",
    countryName: "Denmark",
    countryWithFlag: "🇩🇰 Denmark",
    shortCode: "DK (+45)",
    countryWithCode: "Denmark (+45)",
    value: "+45",
    languageName: "🇩🇰 Dansk",
  },
  {
    flagName: "🇩🇯",
    countryName: "Djibouti",
    countryWithFlag: "🇩🇯 Djibouti",
    shortCode: "DJ (+253)",
    countryWithCode: "Djibouti (+253)",
    value: "+253",
    languageName: "🇩🇯 Français",
  },
  {
    flagName: "🇩🇲",
    countryName: "Dominica",
    countryWithFlag: "🇩🇲 Dominica",
    shortCode: "DM (+1-767)",
    countryWithCode: "Dominica (+1-767)",
    value: "+1-767",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇩🇴",
    countryName: "Dominican Republic",
    countryWithFlag: "🇩🇴 Dominican Republic",
    shortCode: "DO (+1-809)",
    countryWithCode: "Dominican Republic (+1-809)",
    value: "+1-809",
    languageName: "🇩🇴 Español",
  },
  {
    flagName: "🇹🇱",
    countryName: "East Timor",
    countryWithFlag: "🇹🇱 East Timor",
    shortCode: "TL (+670)",
    countryWithCode: "East Timor (+670)",
    value: "+670",
    languageName: "🇹🇱 Tetun",
  },
  {
    flagName: "🇪🇨",
    countryName: "Ecuador",
    countryWithFlag: "🇪🇨 Ecuador",
    shortCode: "EC (+593)",
    countryWithCode: "Ecuador (+593)",
    value: "+593",
    languageName: "🇪🇨 Español",
  },
  {
    flagName: "🇪🇬",
    countryName: "Egypt",
    countryWithFlag: "🇪🇬 Egypt",
    shortCode: "EG (+20)",
    countryWithCode: "Egypt (+20)",
    value: "+20",
    languageName: "🇪🇬 العربية",
  },
  {
    flagName: "🇸🇻",
    countryName: "El Salvador",
    countryWithFlag: "🇸🇻 El Salvador",
    shortCode: "SV (+503)",
    countryWithCode: "El Salvador (+503)",
    value: "+503",
    languageName: "🇸🇻 Español",
  },
  {
    flagName: "🇬🇶",
    countryName: "Equatorial Guinea",
    countryWithFlag: "🇬🇶 Equatorial Guinea",
    shortCode: "GQ (+240)",
    countryWithCode: "Equatorial Guinea (+240)",
    value: "+240",
    languageName: "🇬🇶 Español",
  },
  {
    flagName: "🇪🇷",
    countryName: "Eritrea",
    countryWithFlag: "🇪🇷 Eritrea",
    shortCode: "ER (+291)",
    countryWithCode: "Eritrea (+291)",
    value: "+291",
    languageName: "🇪🇷 عرية الصومال",
  },
  {
    flagName: "🇪🇪",
    countryName: "Estonia",
    countryWithFlag: "🇪🇪 Estonia",
    shortCode: "EE (+372)",
    countryWithCode: "Estonia (+372)",
    value: "+372",
    languageName: "🇪🇪 Eesti",
  },
  {
    flagName: "🇪🇹",
    countryName: "Ethiopia",
    countryWithFlag: "🇪🇹 Ethiopia",
    shortCode: "ET (+251)",
    countryWithCode: "Ethiopia (+251)",
    value: "+251",
    languageName: "🇪🇹 አማርኛ",
  },
  {
    flagName: "🇫🇰",
    countryName: "Falkland Islands",
    countryWithFlag: "🇫🇰 Falkland Islands",
    shortCode: "FK (+500)",
    countryWithCode: "Falkland Islands (+500)",
    value: "+500",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇫🇴",
    countryName: "Faroe Islands",
    countryWithFlag: "🇫🇴 Faroe Islands",
    shortCode: "FO (+298)",
    countryWithCode: "Faroe Islands (+298)",
    value: "+298",
    languageName: "🇫🇴 Føroyskt",
  },
  {
    flagName: "🇫🇯",
    countryName: "Fiji",
    countryWithFlag: "🇫🇯 Fiji",
    shortCode: "FJ (+679)",
    countryWithCode: "Fiji (+679)",
    value: "+679",
    languageName: "🇫🇯 Faka-Fono",
  },
  {
    flagName: "🇫🇮",
    countryName: "Finland",
    countryWithFlag: "🇫🇮 Finland",
    shortCode: "FI (+358)",
    countryWithCode: "Finland (+358)",
    value: "+358",
    languageName: "🇫🇮 Suomi",
  },
  {
    flagName: "🇫🇷",
    countryName: "France",
    countryWithFlag: "🇫🇷 France",
    shortCode: "FR (+33)",
    countryWithCode: "France (+33)",
    value: "+33",
    languageName: "🇫🇷 Français",
  },
  {
    flagName: "🇬🇫",
    countryName: "French Guiana",
    countryWithFlag: "🇬🇫 French Guiana",
    shortCode: "GF (+594)",
    countryWithCode: "French Guiana (+594)",
    value: "+594",
    languageName: "🇬🇫 Français",
  },
  {
    flagName: "🇵🇫",
    countryName: "French Polynesia",
    countryWithFlag: "🇵🇫 French Polynesia",
    shortCode: "PF (+689)",
    countryWithCode: "French Polynesia (+689)",
    value: "+689",
    languageName: "🇵🇫 Français",
  },
  {
    flagName: "🇨🇬",
    countryName: "Republic of the Congo",
    countryWithFlag: "🇨🇬 Republic of the Congo",
    shortCode: "CG (+241)",
    countryWithCode: "Republic of the Congo (+241)",
    value: "+241",
    languageName: "🇨🇬 Français",
  },
  {
    flagName: "🇬🇲",
    countryName: "Gambia",
    countryWithFlag: "🇬🇲 Gambia",
    shortCode: "GM (+220)",
    countryWithCode: "Gambia (+220)",
    value: "+220",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇬🇪",
    countryName: "Georgia",
    countryWithFlag: "🇬🇪 Georgia",
    shortCode: "GE (+995)",
    countryWithCode: "Georgia (+995)",
    value: "+995",
    languageName: "🇬🇪 ქართული",
  },
  {
    flagName: "🇩🇪",
    countryName: "Germany",
    countryWithFlag: "🇩🇪 Germany",
    shortCode: "DE (+49)",
    countryWithCode: "Germany (+49)",
    value: "+49",
    languageName: "🇩🇪 Deutsch",
  },
  {
    flagName: "🇬🇭",
    countryName: "Ghana",
    countryWithFlag: "🇬🇭 Ghana",
    shortCode: "GH (+233)",
    countryWithCode: "Ghana (+233)",
    value: "+233",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇬🇮",
    countryName: "Gibraltar",
    countryWithFlag: "🇬🇮 Gibraltar",
    shortCode: "GI (+350)",
    countryWithCode: "Gibraltar (+350)",
    value: "+350",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇬🇷",
    countryName: "Greece",
    countryWithFlag: "🇬🇷 Greece",
    shortCode: "GR (+30)",
    countryWithCode: "Greece (+30)",
    value: "+30",
    languageName: "🇬🇷 Ελληνικά",
  },
  {
    flagName: "🇬🇱",
    countryName: "Greenland",
    countryWithFlag: "🇬🇱 Greenland",
    shortCode: "GL (+299)",
    countryWithCode: "Greenland (+299)",
    value: "+299",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇬🇩",
    countryName: "Grenada",
    countryWithFlag: "🇬🇩 Grenada",
    shortCode: "GD (+1-473)",
    countryWithCode: "Grenada (+1-473)",
    value: "+1-473",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇬🇵",
    countryName: "Guadeloupe",
    countryWithFlag: "🇬🇵 Guadeloupe",
    shortCode: "GP (+590)",
    countryWithCode: "Guadeloupe (+590)",
    value: "+590",
    languageName: "🇬🇵 Français",
  },
  {
    flagName: "🇬🇺",
    countryName: "Guam",
    countryWithFlag: "🇬🇺 Guam",
    shortCode: "GU (+1-671)",
    countryWithCode: "Guam (+1-671)",
    value: "+1-671",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇬🇹",
    countryName: "Guatemala",
    countryWithFlag: "🇬🇹 Guatemala",
    shortCode: "GT (+502)",
    countryWithCode: "Guatemala (+502)",
    value: "+502",
    languageName: "🇬🇹 Español",
  },
  {
    flagName: "🇬🇬",
    countryName: "Guernsey",
    countryWithFlag: "🇬🇬 Guernsey",
    shortCode: "GG (+44-1481)",
    countryWithCode: "Guernsey (+44-1481)",
    value: "+44-1481",
    languageName: "🇬🇬 English",
  },
  {
    flagName: "🇬🇳",
    countryName: "Guinea",
    countryWithFlag: "🇬🇳 Guinea",
    shortCode: "GN (+224)",
    countryWithCode: "Guinea (+224)",
    value: "+224",
    languageName: "🇬🇳 Français",
  },
  {
    flagName: "🇬🇼",
    countryName: "Guinea-Bissau",
    countryWithFlag: "🇬🇼 Guinea-Bissau",
    shortCode: "GW (+245)",
    countryWithCode: "Guinea-Bissau (+245)",
    value: "+245",
    languageName: "🇬🇼 Português",
  },
  {
    flagName: "🇬🇾",
    countryName: "Guyana",
    countryWithFlag: "🇬🇾 Guyana",
    shortCode: "GY (+592)",
    countryWithCode: "Guyana (+592)",
    value: "+592",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇭🇹",
    countryName: "Haiti",
    countryWithFlag: "🇭🇹 Haiti",
    shortCode: "HT (+509)",
    countryWithCode: "Haiti (+509)",
    value: "+509",
    languageName: "🇭🇹 Français",
  },
  {
    flagName: "🇭🇳",
    countryName: "Honduras",
    countryWithFlag: "🇭🇳 Honduras",
    shortCode: "HN (+504)",
    countryWithCode: "Honduras (+504)",
    value: "+504",
    languageName: "🇭🇳 Español",
  },
  {
    flagName: "🇭🇰",
    countryName: "Hong Kong",
    countryWithFlag: "🇭🇰 Hong Kong",
    shortCode: "HK (+852)",
    countryWithCode: "Hong Kong (+852)",
    value: "+852",
    languageName: "🇭🇰 中文",
  },
  {
    flagName: "🇭🇺",
    countryName: "Hungary",
    countryWithFlag: "🇭🇺 Hungary",
    shortCode: "HU (+36)",
    countryWithCode: "Hungary (+36)",
    value: "+36",
    languageName: "🇭🇺 Magyar",
  },
  {
    flagName: "🇮🇸",
    countryName: "Iceland",
    countryWithFlag: "🇮🇸 Iceland",
    shortCode: "IS (+354)",
    countryWithCode: "Iceland (+354)",
    value: "+354",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇮🇳",
    countryName: "India",
    countryWithFlag: "🇮🇳 India",
    shortCode: "IN (+91)",
    countryWithCode: "India (+91)",
    value: "+91",
    languageName: "🇮🇳 हिन्दी",
  },
  {
    flagName: "🇮🇩",
    countryName: "Indonesia",
    countryWithFlag: "🇮🇩 Indonesia",
    shortCode: "ID (+62)",
    countryWithCode: "Indonesia (+62)",
    value: "+62",
    languageName: "🇮🇩 Bahasa Indonesia",
  },
  {
    flagName: "🇮🇷",
    countryName: "Iran",
    countryWithFlag: "🇮🇷 Iran",
    shortCode: "IR (+98)",
    countryWithCode: "Iran (+98)",
    value: "+98",
    languageName: "🇮🇷 فارسی",
  },
  {
    flagName: "🇮🇶",
    countryName: "Iraq",
    countryWithFlag: "🇮🇶 Iraq",
    shortCode: "IQ (+964)",
    countryWithCode: "Iraq (+964)",
    value: "+964",
    languageName: "🇮🇶 العربية",
  },
  {
    flagName: "🇮🇪",
    countryName: "Ireland",
    countryWithFlag: "🇮🇪 Ireland",
    shortCode: "IE (+353)",
    countryWithCode: "Ireland (+353)",
    value: "+353",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇮🇲",
    countryName: "Isle of Man",
    countryWithFlag: "🇮🇲 Isle of Man",
    shortCode: "IM (+44-1624)",
    countryWithCode: "Isle of Man (+44-1624)",
    value: "+44-1624",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇮🇱",
    countryName: "Israel",
    countryWithFlag: "🇮🇱 Israel",
    shortCode: "IL (+972)",
    countryWithCode: "Israel (+972)",
    value: "+972",
    languageName: "🇮🇱 עברית",
  },
  {
    flagName: "🇮🇹",
    countryName: "Italy",
    countryWithFlag: "🇮🇹 Italy",
    shortCode: "IT (+39)",
    countryWithCode: "Italy (+39)",
    value: "+39",
    languageName: "🇮🇹 Italiano",
  },
  {
    flagName: "🇨🇮",
    countryName: "Ivory Coast",
    countryWithFlag: "🇨🇮 Ivory Coast",
    shortCode: "CI (+225)",
    countryWithCode: "Ivory Coast (+225)",
    value: "+225",
    languageName: "🇨🇮 Français",
  },
  {
    flagName: "🇯🇲",
    countryName: "Jamaica",
    countryWithFlag: "🇯🇲 Jamaica",
    shortCode: "JM (+1-876)",
    countryWithCode: "Jamaica (+1-876)",
    value: "+1-876",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇯🇵",
    countryName: "Japan",
    countryWithFlag: "🇯🇵 Japan",
    shortCode: "JP (+81)",
    countryWithCode: "Japan (+81)",
    value: "+81",
    languageName: "🇯🇵 日本語",
  },
  {
    flagName: "🇯🇪",
    countryName: "Jersey",
    countryWithFlag: "🇯🇪 Jersey",
    shortCode: "JE (+44-1534)",
    countryWithCode: "Jersey (+44-1534)",
    value: "+44-1534",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇯🇴",
    countryName: "Jordan",
    countryWithFlag: "🇯🇴 Jordan",
    shortCode: "JO (+962)",
    countryWithCode: "Jordan (+962)",
    value: "+962",
    languageName: "🇯🇴 العربية",
  },
  {
    flagName: "🇰🇿",
    countryName: "Kazakhstan",
    countryWithFlag: "🇰🇿 Kazakhstan",
    shortCode: "KZ (+7)",
    countryWithCode: "Kazakhstan (+7)",
    value: "+7",
    languageName: "🇰🇿 Қазақша",
  },
  {
    flagName: "🇰🇪",
    countryName: "Kenya",
    countryWithFlag: "🇰🇪 Kenya",
    shortCode: "KE (+254)",
    countryWithCode: "Kenya (+254)",
    value: "+254",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇰🇮",
    countryName: "Kiribati",
    countryWithFlag: "🇰🇮 Kiribati",
    shortCode: "KI (+686)",
    countryWithCode: "Kiribati (+686)",
    value: "+686",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇰🇼",
    countryName: "Kuwait",
    countryWithFlag: "🇰🇼 Kuwait",
    shortCode: "KW (+965)",
    countryWithCode: "Kuwait (+965)",
    value: "+965",
    languageName: "🇰🇼 العربية",
  },
  {
    flagName: "🇰🇬",
    countryName: "Kyrgyzstan",
    countryWithFlag: "🇰🇬 Kyrgyzstan",
    shortCode: "KG (+996)",
    countryWithCode: "Kyrgyzstan (+996)",
    value: "+996",
    languageName: "🇰🇬 Кыргызча",
  },
  {
    flagName: "🇱🇦",
    countryName: "Laos",
    countryWithFlag: "🇱🇦 Laos",
    shortCode: "LA (+856)",
    countryWithCode: "Laos (+856)",
    value: "+856",
    languageName: "🇱🇦 ລາວ",
  },
  {
    flagName: "🇱🇻",
    countryName: "Latvia",
    countryWithFlag: "🇱🇻 Latvia",
    shortCode: "LV (+371)",
    countryWithCode: "Latvia (+371)",
    value: "+371",
    languageName: "🇱🇻 Latviešu",
  },
  {
    flagName: "🇱🇧",
    countryName: "Lebanon",
    countryWithFlag: "🇱🇧 Lebanon",
    shortCode: "LB (+961)",
    countryWithCode: "Lebanon (+961)",
    value: "+961",
    languageName: "🇱🇧 العربية",
  },
  {
    flagName: "🇱🇸",
    countryName: "Lesotho",
    countryWithFlag: "🇱🇸 Lesotho",
    shortCode: "LS (+266)",
    countryWithCode: "Lesotho (+266)",
    value: "+266",
    languageName: "🇱🇸 Sesotho",
  },
  {
    flagName: "🇱🇷",
    countryName: "Liberia",
    countryWithFlag: "🇱🇷 Liberia",
    shortCode: "LR (+231)",
    countryWithCode: "Liberia (+231)",
    value: "+231",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇱🇾",
    countryName: "Libya",
    countryWithFlag: "🇱🇾 Libya",
    shortCode: "LY (+218)",
    countryWithCode: "Libya (+218)",
    value: "+218",
    languageName: "🇱🇾 العربية",
  },
  {
    flagName: "🇱🇮",
    countryName: "Liechtenstein",
    countryWithFlag: "🇱🇮 Liechtenstein",
    shortCode: "LI (+423)",
    countryWithCode: "Liechtenstein (+423)",
    value: "+423",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇱🇹",
    countryName: "Lithuania",
    countryWithFlag: "🇱🇹 Lithuania",
    shortCode: "LT (+370)",
    countryWithCode: "Lithuania (+370)",
    value: "+370",
    languageName: "🇱🇹 Lietuvių",
  },
  {
    flagName: "🇱🇺",
    countryName: "Luxembourg",
    countryWithFlag: "🇱🇺 Luxembourg",
    shortCode: "LU (+352)",
    countryWithCode: "Luxembourg (+352)",
    value: "+352",
    languageName: "🇱🇺 Lëtzebuergesch",
  },
  {
    flagName: "🇲🇴",
    countryName: "Macau",
    countryWithFlag: "🇲🇴 Macau",
    shortCode: "MO (+853)",
    countryWithCode: "Macau (+853)",
    value: "+853",
    languageName: "🇲🇴 中文",
  },
  {
    flagName: "🇲🇰",
    countryName: "Macedonia",
    countryWithFlag: "🇲🇰 Macedonia",
    shortCode: "MK (+389)",
    countryWithCode: "Macedonia (+389)",
    value: "+389",
    languageName: "🇲🇰 Македонски",
  },
  {
    flagName: "🇲🇬",
    countryName: "Madagascar",
    countryWithFlag: "🇲🇬 Madagascar",
    shortCode: "MG (+261)",
    countryWithCode: "Madagascar (+261)",
    value: "+261",
    languageName: "🇲🇬 Malagasy",
  },
  {
    flagName: "🇲🇼",
    countryName: "Malawi",
    countryWithFlag: "🇲🇼 Malawi",
    shortCode: "MW (+265)",
    countryWithCode: "Malawi (+265)",
    value: "+265",
    languageName: "🇲🇼 Chichewa",
  },
  {
    flagName: "🇲🇾",
    countryName: "Malaysia",
    countryWithFlag: "🇲🇾 Malaysia",
    shortCode: "MY (+60)",
    countryWithCode: "Malaysia (+60)",
    value: "+60",
    languageName: "🇲🇾 Bahasa Melayu",
  },
  {
    flagName: "🇲🇻",
    countryName: "Maldives",
    countryWithFlag: "🇲🇻 Maldives",
    shortCode: "MV (+960)",
    countryWithCode: "Maldives (+960)",
    value: "+960",
    languageName: "🇲🇻 Divehi",
  },
  {
    flagName: "🇲🇱",
    countryName: "Mali",
    countryWithFlag: "🇲🇱 Mali",
    shortCode: "ML (+223)",
    countryWithCode: "Mali (+223)",
    value: "+223",
    languageName: "🇲🇱 Malinke",
  },
  {
    flagName: "🇲🇹",
    countryName: "Malta",
    countryWithFlag: "🇲🇹 Malta",
    shortCode: "MT (+356)",
    countryWithCode: "Malta (+356)",
    value: "+356",
    languageName: "🇲🇹 Malti",
  },
  {
    flagName: "🇲🇭",
    countryName: "Marshall Islands",
    countryWithFlag: "🇲🇭 Marshall Islands",
    shortCode: "MH (+692)",
    countryWithCode: "Marshall Islands (+692)",
    value: "+692",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇲🇶",
    countryName: "Martinique",
    countryWithFlag: "🇲🇶 Martinique",
    shortCode: "MQ (+596)",
    countryWithCode: "Martinique (+596)",
    value: "+596",
    languageName: "🇲🇶 Français",
  },
  {
    flagName: "🇲🇷",
    countryName: "Mauritania",
    countryWithFlag: "🇲🇷 Mauritania",
    shortCode: "MR (+222)",
    countryWithCode: "Mauritania (+222)",
    value: "+222",
    languageName: "🇲🇷 Français",
  },
  {
    flagName: "🇲🇺",
    countryName: "Mauritius",
    countryWithFlag: "🇲🇺 Mauritius",
    shortCode: "MU (+230)",
    countryWithCode: "Mauritius (+230)",
    value: "+230",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇾🇹",
    countryName: "Mayotte",
    countryWithFlag: "🇾🇹 Mayotte",
    shortCode: "YT (+262)",
    countryWithCode: "Mayotte (+262)",
    value: "+262",
    languageName: "🇾🇹 Français",
  },
  {
    flagName: "🇲🇱",
    countryName: "Mexico",
    countryWithFlag: "🇲🇱 Mexico",
    shortCode: "MX (+52)",
    countryWithCode: "Mexico (+52)",
    value: "+52",
    languageName: "🇲🇱 Español",
  },
  {
    flagName: "🇫🇲",
    countryName: "Micronesia",
    countryWithFlag: "🇫🇲 Micronesia",
    shortCode: "FM (+691)",
    countryWithCode: "Micronesia (+691)",
    value: "+691",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇲🇩",
    countryName: "Moldova",
    countryWithFlag: "🇲🇩 Moldova",
    shortCode: "MD (+373)",
    countryWithCode: "Moldova (+373)",
    value: "+373",
    languageName: "🇲🇩 Moldovenește",
  },
  {
    flagName: "🇲🇨",
    countryName: "Monaco",
    countryWithFlag: "🇲🇨 Monaco",
    shortCode: "MC (+377)",
    countryWithCode: "Monaco (+377)",
    value: "+377",
    languageName: "🇲🇨 Français",
  },
  {
    flagName: "🇲🇳",
    countryName: "Mongolia",
    countryWithFlag: "🇲🇳 Mongolia",
    shortCode: "MN (+976)",
    countryWithCode: "Mongolia (+976)",
    value: "+976",
    languageName: "🇲🇳 Монгол",
  },
  {
    flagName: "🇲🇪",
    countryName: "Montenegro",
    countryWithFlag: "🇲🇪 Montenegro",
    shortCode: "ME (+382)",
    countryWithCode: "Montenegro (+382)",
    value: "+382",
    languageName: "🇲🇪 Crnogorski",
  },
  {
    flagName: "🇲🇸",
    countryName: "Montserrat",
    countryWithFlag: "🇲🇸 Montserrat",
    shortCode: "MS (+1-664)",
    countryWithCode: "Montserrat (+1-664)",
    value: "+1-664",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇲🇦",
    countryName: "Morocco",
    countryWithFlag: "🇲🇦 Morocco",
    shortCode: "MA (+212)",
    countryWithCode: "Morocco (+212)",
    value: "+212",
    languageName: "🇲🇦 العربية",
  },
  {
    flagName: "🇲🇿",
    countryName: "Mozambique",
    countryWithFlag: "🇲🇿 Mozambique",
    shortCode: "MZ (+258)",
    countryWithCode: "Mozambique (+258)",
    value: "+258",
    languageName: "🇲🇿 Português",
  },
  {
    flagName: "🇲🇲",
    countryName: "Myanmar",
    countryWithFlag: "🇲🇲 Myanmar",
    shortCode: "MM (+95)",
    countryWithCode: "Myanmar (+95)",
    value: "+95",
    languageName: "🇲🇲 ဗမာစာ",
  },
  {
    flagName: "🇳🇦",
    countryName: "Namibia",
    countryWithFlag: "🇳🇦 Namibia",
    shortCode: "NA (+264)",
    countryWithCode: "Namibia (+264)",
    value: "+264",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇳🇷",
    countryName: "Nauru",
    countryWithFlag: "🇳🇷 Nauru",
    shortCode: "NR (+674)",
    countryWithCode: "Nauru (+674)",
    value: "+674",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇳🇵",
    countryName: "Nepal",
    countryWithFlag: "🇳🇵 Nepal",
    shortCode: "NP (+977)",
    countryWithCode: "Nepal (+977)",
    value: "+977",
    languageName: "🇳🇵 नेपाली",
  },
  {
    flagName: "🇳🇱",
    countryName: "Netherlands",
    countryWithFlag: "🇳🇱 Netherlands",
    shortCode: "NL (+31)",
    countryWithCode: "Netherlands (+31)",
    value: "+31",
    languageName: "🇳🇱 Nederlands",
  },
  {
    flagName: "🇳🇱",
    countryName: "Netherlands Antilles",
    countryWithFlag: "🇳🇱 Netherlands Antilles",
    shortCode: "AN (+599)",
    countryWithCode: "Netherlands Antilles (+599)",
    value: "+599",
    languageName: "🇳🇱 Papiamento",
  },
  {
    flagName: "🇳🇨",
    countryName: "New Caledonia",
    countryWithFlag: "🇳🇨 New Caledonia",
    shortCode: "NC (+687)",
    countryWithCode: "New Caledonia (+687)",
    value: "+687",
    languageName: "🇳🇨 Nouveaux-Calédoniens",
  },
  {
    flagName: "🇳🇿",
    countryName: "New Zealand",
    countryWithFlag: "🇳🇿 New Zealand",
    shortCode: "NZ (+64)",
    countryWithCode: "New Zealand (+64)",
    value: "+64",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇳🇮",
    countryName: "Nicaragua",
    countryWithFlag: "🇳🇮 Nicaragua",
    shortCode: "NI (+505)",
    countryWithCode: "Nicaragua (+505)",
    value: "+505",
    languageName: "🇳🇮 Español",
  },
  {
    flagName: "🇳🇪",
    countryName: "Niger",
    countryWithFlag: "🇳🇪 Niger",
    shortCode: "NE (+227)",
    countryWithCode: "Niger (+227)",
    value: "+227",
    languageName: "🇳🇪 Français",
  },
  {
    flagName: "🇳🇬",
    countryName: "Nigeria",
    countryWithFlag: "🇳🇬 Nigeria",
    shortCode: "NG (+234)",
    countryWithCode: "Nigeria (+234)",
    value: "+234",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇳🇺",
    countryName: "Niue",
    countryWithFlag: "🇳🇺 Niue",
    shortCode: "NU (+683)",
    countryWithCode: "Niue (+683)",
    value: "+683",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇳🇫",
    countryName: "Norfolk Island",
    countryWithFlag: "🇳🇫 Norfolk Island",
    shortCode: "NF (+672)",
    countryWithCode: "Norfolk Island (+672)",
    value: "+672",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇰🇵",
    countryName: "North Korea",
    countryWithFlag: "🇰🇵 North Korea",
    shortCode: "KP (+850)",
    countryWithCode: "North Korea (+850)",
    value: "+850",
    languageName: "🇰🇵 한국어",
  },
  {
    flagName: "🇲🇵",
    countryName: "Northern Mariana Islands",
    countryWithFlag: "🇲🇵 Northern Mariana Islands",
    shortCode: "MP (+1-670)",
    countryWithCode: "Northern Mariana Islands (+1-670)",
    value: "+1-670",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇳🇴",
    countryName: "Norway",
    countryWithFlag: "🇳🇴 Norway",
    shortCode: "NO (+47)",
    countryWithCode: "Norway (+47)",
    value: "+47",
    languageName: "🇳🇴 Norsk",
  },
  {
    flagName: "🇴🇲",
    countryName: "Oman",
    countryWithFlag: "🇴🇲 Oman",
    shortCode: "OM (+968)",
    countryWithCode: "Oman (+968)",
    value: "+968",
    languageName: "🇴🇲 العربية",
  },
  {
    flagName: "🇵🇰",
    countryName: "Pakistan",
    countryWithFlag: "🇵🇰 Pakistan",
    shortCode: "PK (+92)",
    countryWithCode: "Pakistan (+92)",
    value: "+92",
    languageName: "🇵🇰 اردو",
  },
  {
    flagName: "🇵🇼",
    countryName: "Palau",
    countryWithFlag: "🇵🇼 Palau",
    shortCode: "PW (+680)",
    countryWithCode: "Palau (+680)",
    value: "+680",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇵🇸",
    countryName: "Palestine",
    countryWithFlag: "🇵🇸 Palestine",
    shortCode: "PS (+970)",
    countryWithCode: "Palestine (+970)",
    value: "+970",
    languageName: "🇵🇸 العربية",
  },
  {
    flagName: "🇨🇷",
    countryName: "Costa Rica",
    countryWithFlag: "🇨🇷 Costa Rica",
    shortCode: "CR (+506)",
    countryWithCode: "Costa Rica (+506)",
    value: "+506",
    languageName: "🇨🇷 Español",
  },
  {
    flagName: "🇵🇬",
    countryName: "Papua New Guinea",
    countryWithFlag: "🇵🇬 Papua New Guinea",
    shortCode: "PG (+675)",
    countryWithCode: "Papua New Guinea (+675)",
    value: "+675",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇵🇾",
    countryName: "Paraguay",
    countryWithFlag: "🇵🇾 Paraguay",
    shortCode: "PY (+595)",
    countryWithCode: "Paraguay (+595)",
    value: "+595",
    languageName: "🇵🇾 Español",
  },
  {
    flagName: "🇵🇪",
    countryName: "Peru",
    countryWithFlag: "🇵🇪 Peru",
    shortCode: "PE (+51)",
    countryWithCode: "Peru (+51)",
    value: "+51",
    languageName: "🇵🇪 Español",
  },
  {
    flagName: "🇵🇭",
    countryName: "Philippines",
    countryWithFlag: "🇵🇭 Philippines",
    shortCode: "PH (+63)",
    countryWithCode: "Philippines (+63)",
    value: "+63",
    languageName: "🇵🇭 Filipino",
  },
  {
    flagName: "🇵🇱",
    countryName: "Poland",
    countryWithFlag: "🇵🇱 Poland",
    shortCode: "PL (+48)",
    countryWithCode: "Poland (+48)",
    value: "+48",
    languageName: "🇵🇱 Polski",
  },
  {
    flagName: "🇵🇹",
    countryName: "Portugal",
    countryWithFlag: "🇵🇹 Portugal",
    shortCode: "PT (+351)",
    countryWithCode: "Portugal (+351)",
    value: "+351",
    languageName: "🇵🇹 Português",
  },
  {
    flagName: "🇵🇷",
    countryName: "Puerto Rico",
    countryWithFlag: "🇵🇷 Puerto Rico",
    shortCode: "PR (+1-787)",
    countryWithCode: "Puerto Rico (+1-787)",
    value: "+1-787",
    languageName: "🇵🇷 Español",
  },
  {
    flagName: "🇶🇦",
    countryName: "Qatar",
    countryWithFlag: "🇶🇦 Qatar",
    shortCode: "QA (+974)",
    countryWithCode: "Qatar (+974)",
    value: "+974",
    languageName: "🇶🇦 العربية",
  },
  {
    flagName: "🇨🇬",
    countryName: "Republic of the Congo",
    countryWithFlag: "🇨🇬 Republic of the Congo",
    shortCode: "CG (+241)",
    countryWithCode: "Republic of the Congo (+241)",
    value: "+241",
    languageName: "🇨🇬 Français",
  },
  {
    flagName: "🇷🇪",
    countryName: "Reunion",
    countryWithFlag: "🇷🇪 Reunion",
    shortCode: "RE (+262)",
    countryWithCode: "Reunion (+262)",
    value: "+262",
    languageName: "🇷🇪 Français",
  },
  {
    flagName: "🇷🇴",
    countryName: "Romania",
    countryWithFlag: "🇷🇴 Romania",
    shortCode: "RO (+40)",
    countryWithCode: "Romania (+40)",
    value: "+40",
    languageName: "🇷🇴 Română",
  },
  {
    flagName: "🇷🇺",
    countryName: "Russia",
    countryWithFlag: "🇷🇺 Russia",
    shortCode: "RU (+7)",
    countryWithCode: "Russia (+7)",
    value: "+7",
    languageName: "🇷🇺 Русский",
  },
  {
    flagName: "🇷🇼",
    countryName: "Rwanda",
    countryWithFlag: "🇷🇼 Rwanda",
    shortCode: "RW (+250)",
    countryWithCode: "Rwanda (+250)",
    value: "+250",
    languageName: "🇷🇼 Kinyarwanda",
  },
  {
    flagName: "🇧🇱",
    countryName: "Saint Barthelemy",
    countryWithFlag: "🇧🇱 Saint Barthelemy",
    shortCode: "BL (+590)",
    countryWithCode: "Saint Barthelemy (+590)",
    value: "+590",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇸🇭",
    countryName: "Saint Helena",
    countryWithFlag: "🇸🇭 Saint Helena",
    shortCode: "SH (+290)",
    countryWithCode: "Saint Helena (+290)",
    value: "+290",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇰🇳",
    countryName: "Saint Kitts and Nevis",
    countryWithFlag: "🇰🇳 Saint Kitts and Nevis",
    shortCode: "KN (+1-869)",
    countryWithCode: "Saint Kitts and Nevis (+1-869)",
    value: "+1-869",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇱🇨",
    countryName: "Saint Lucia",
    countryWithFlag: "🇱🇨 Saint Lucia",
    shortCode: "LC (+1-758)",
    countryWithCode: "Saint Lucia (+1-758)",
    value: "+1-758",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇲🇫",
    countryName: "Saint Martin",
    countryWithFlag: "🇲🇫 Saint Martin",
    shortCode: "MF (+590)",
    countryWithCode: "Saint Martin (+590)",
    value: "+590",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇵🇲",
    countryName: "Saint Pierre and Miquelon",
    countryWithFlag: "🇵🇲 Saint Pierre and Miquelon",
    shortCode: "PM (+508)",
    countryWithCode: "Saint Pierre and Miquelon (+508)",
    value: "+508",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇻🇨",
    countryName: "Saint Vincent and the Grenadines",
    countryWithFlag: "🇻🇨 Saint Vincent and the Grenadines",
    shortCode: "VC (+1-784)",
    countryWithCode: "Saint Vincent and the Grenadines (+1-784)",
    value: "+1-784",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇼🇸",
    countryName: "Samoa",
    countryWithFlag: "🇼🇸 Samoa",
    shortCode: "WS (+685)",
    countryWithCode: "Samoa (+685)",
    value: "+685",
    languageName: "🇼🇸 Samoan",
  },
  {
    flagName: "🇸🇲",
    countryName: "San Marino",
    countryWithFlag: "🇸🇲 San Marino",
    shortCode: "SM (+378)",
    countryWithCode: "San Marino (+378)",
    value: "+378",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇸🇳",
    countryName: "Senegal",
    countryWithFlag: "🇸🇳 Senegal",
    shortCode: "SN (+221)",
    countryWithCode: "Senegal (+221)",
    value: "+221",
    languageName: "🇸🇳 Français",
  },
  {
    flagName: "🇷🇸",
    countryName: "Serbia",
    countryWithFlag: "🇷🇸 Serbia",
    shortCode: "RS (+381)",
    countryWithCode: "Serbia (+381)",
    value: "+381",
    languageName: "🇷🇸 Српски",
  },
  {
    flagName: "🇸🇨",
    countryName: "Seychelles",
    countryWithFlag: "🇸🇨 Seychelles",
    shortCode: "SC (+248)",
    countryWithCode: "Seychelles (+248)",
    value: "+248",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇱🇷",
    countryName: "Sierra Leone",
    countryWithFlag: "🇱🇷 Sierra Leone",
    shortCode: "SL (+232)",
    countryWithCode: "Sierra Leone (+232)",
    value: "+232",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇸🇬",
    countryName: "Singapore",
    countryWithFlag: "🇸🇬 Singapore",
    shortCode: "SG (+65)",
    countryWithCode: "Singapore (+65)",
    value: "+65",
    languageName: "🇬🇧 English",
  },
  {
    flagName: "🇸🇽",
    countryName: "Sint Maarten",
    countryWithFlag: "🇸🇽 Sint Maarten",
    shortCode: "SX (+1-721)",
    countryWithCode: "Sint Maarten (+1-721)",
    value: "+1-721",
  },
  {
    flagName: "🇸🇰",
    countryName: "Slovakia",
    countryWithFlag: "🇸🇰 Slovakia",
    shortCode: "SK (+421)",
    countryWithCode: "Slovakia (+421)",
    value: "+421",
  },
  {
    flagName: "🇸🇮",
    countryName: "Slovenia",
    countryWithFlag: "🇸🇮 Slovenia",
    shortCode: "SI (+386)",
    countryWithCode: "Slovenia (+386)",
    value: "+386",
  },
  {
    flagName: "🇸��",
    countryName: "Solomon Islands",
    countryWithFlag: "🇸🇧 Solomon Islands",
    shortCode: "SB (+677)",
    countryWithCode: "Solomon Islands (+677)",
    value: "+677",
  },
  {
    flagName: "🇿🇦",
    countryName: "South Africa",
    countryWithFlag: "🇿🇦 South Africa",
    shortCode: "ZA (+27)",
    countryWithCode: "South Africa (+27)",
    value: "+27",
  },
  {
    flagName: "🇰🇷",
    countryName: "South Korea",
    countryWithFlag: "🇰🇷 South Korea",
    shortCode: "KR (+82)",
    countryWithCode: "South Korea (+82)",
    value: "+82",
  },
  {
    flagName: "🇸🇸",
    countryName: "South Sudan",
    countryWithFlag: "🇸🇸 South Sudan",
    shortCode: "SS (+211)",
    countryWithCode: "South Sudan (+211)",
    value: "+211",
  },
  {
    flagName: "🇪🇸",
    countryName: "Spain",
    countryWithFlag: "🇪🇸 Spain",
    shortCode: "ES (+34)",
    countryWithCode: "Spain (+34)",
    value: "+34",
  },
  {
    flagName: "🇱🇰",
    countryName: "Sri Lanka",
    countryWithFlag: "🇱🇰 Sri Lanka",
    shortCode: "LK (+94)",
    countryWithCode: "Sri Lanka (+94)",
    value: "+94",
  },
  {
    flagName: "🇸🇩",
    countryName: "Sudan",
    countryWithFlag: "🇸🇩 Sudan",
    shortCode: "SD (+249)",
    countryWithCode: "Sudan (+249)",
    value: "+249",
  },
  {
    flagName: "🇸🇷",
    countryName: "Suriname",
    countryWithFlag: "🇸🇷 Suriname",
    shortCode: "SR (+597)",
    countryWithCode: "Suriname (+597)",
    value: "+597",
  },
  {
    flagName: "🇸🇯",
    countryName: "Svalbard and Jan Mayen",
    countryWithFlag: "🇸🇯 Svalbard and Jan Mayen",
    shortCode: "SJ (+47)",
    countryWithCode: "Svalbard and Jan Mayen (+47)",
    value: "+47",
  },
  {
    flagName: "🇿🇿",
    countryName: "Swaziland",
    countryWithFlag: "🇿🇿 Swaziland",
    shortCode: "SZ (+268)",
    countryWithCode: "Swaziland (+268)",
    value: "+268",
  },
  {
    flagName: "🇸🇪",
    countryName: "Sweden",
    countryWithFlag: "🇸🇪 Sweden",
    shortCode: "SE (+46)",
    countryWithCode: "Sweden (+46)",
    value: "+46",
  },
  {
    flagName: "🇨🇭",
    countryName: "Switzerland",
    countryWithFlag: "🇨🇭 Switzerland",
    shortCode: "CH (+41)",
    countryWithCode: "Switzerland (+41)",
    value: "+41",
  },
  {
    flagName: "🇸🇾",
    countryName: "Syria",
    countryWithFlag: "🇸🇾 Syria",
    shortCode: "SY (+963)",
    countryWithCode: "Syria (+963)",
    value: "+963",
  },
  {
    flagName: "🇹🇼",
    countryName: "Taiwan",
    countryWithFlag: "🇹🇼 Taiwan",
    shortCode: "TW (+886)",
    countryWithCode: "Taiwan (+886)",
    value: "+886",
  },
  {
    flagName: "🇹🇯",
    countryName: "Tajikistan",
    countryWithFlag: "🇹🇯 Tajikistan",
    shortCode: "TJ (+992)",
    countryWithCode: "Tajikistan (+992)",
    value: "+992",
  },
  {
    flagName: "🇹🇿",
    countryName: "Tanzania",
    countryWithFlag: "🇹🇿 Tanzania",
    shortCode: "TZ (+255)",
    countryWithCode: "Tanzania (+255)",
    value: "+255",
  },
  {
    flagName: "🇹🇭",
    countryName: "Thailand",
    countryWithFlag: "🇹🇭 Thailand",
    shortCode: "TH (+66)",
    countryWithCode: "Thailand (+66)",
    value: "+66",
  },
  {
    flagName: "🇹🇬",
    countryName: "Togo",
    countryWithFlag: "🇹🇬 Togo",
    shortCode: "TG (+228)",
    countryWithCode: "Togo (+228)",
    value: "+228",
  },
  {
    flagName: "🇹🇰",
    countryName: "Tokelau",
    countryWithFlag: "🇹🇰 Tokelau",
    shortCode: "TK (+690)",
    countryWithCode: "Tokelau (+690)",
    value: "+690",
  },
  {
    flagName: "🇹��",
    countryName: "Tonga",
    countryWithFlag: "🇹🇴 Tonga",
    shortCode: "TO (+676)",
    countryWithCode: "Tonga (+676)",
    value: "+676",
  },
  {
    flagName: "🇹🇹",
    countryName: "Trinidad and Tobago",
    countryWithFlag: "🇹🇹 Trinidad and Tobago",
    shortCode: "TT (+1-868)",
    countryWithCode: "Trinidad and Tobago (+1-868)",
    value: "+1-868",
  },
  {
    flagName: "🇹🇳",
    countryName: "Tunisia",
    countryWithFlag: "🇹🇳 Tunisia",
    shortCode: "TN (+216)",
    countryWithCode: "Tunisia (+216)",
    value: "+216",
  },
  {
    flagName: "🇹🇷",
    countryName: "Turkey",
    countryWithFlag: "🇹🇷 Turkey",
    shortCode: "TR (+90)",
    countryWithCode: "Turkey (+90)",
    value: "+90",
  },
  {
    flagName: "🇹🇲",
    countryName: "Turkmenistan",
    countryWithFlag: "🇹🇲 Turkmenistan",
    shortCode: "TM (+993)",
    countryWithCode: "Turkmenistan (+993)",
    value: "+993",
  },
  {
    flagName: "🇹🇨",
    countryName: "Turks and Caicos Islands",
    countryWithFlag: "🇹🇨 Turks and Caicos Islands",
    shortCode: "TC (+1-649)",
    countryWithCode: "Turks and Caicos Islands (+1-649)",
    value: "+1-649",
  },
  {
    flagName: "🇹🇻",
    countryName: "Tuvalu",
    countryWithFlag: "🇹🇻 Tuvalu",
    shortCode: "TV (+688)",
    countryWithCode: "Tuvalu (+688)",
    value: "+688",
  },
  {
    flagName: "🇺��",
    countryName: "Uganda",
    countryWithFlag: "🇺🇬 Uganda",
    shortCode: "UG (+256)",
    countryWithCode: "Uganda (+256)",
    value: "+256",
  },
  {
    flagName: "🇺🇦",
    countryName: "Ukraine",
    countryWithFlag: "🇺🇦 Ukraine",
    shortCode: "UA (+380)",
    countryWithCode: "Ukraine (+380)",
    value: "+380",
  },
  {
    flagName: "🇦🇪",
    countryName: "United Arab Emirates",
    countryWithFlag: "🇦🇪 United Arab Emirates",
    shortCode: "AE (+971)",
    countryWithCode: "United Arab Emirates (+971)",
    value: "+971",
  },
  {
    flagName: "🇬🇧",
    countryName: "United Kingdom",
    countryWithFlag: "🇬🇧 United Kingdom",
    shortCode: "GB (+44)",
    countryWithCode: "United Kingdom (+44)",
    value: "+44",
  },
  {
    flagName: "🇺🇸",
    countryName: "United States",
    countryWithFlag: "🇺🇸 United States",
    shortCode: "US (+1)",
    countryWithCode: "United States (+1)",
    value: "+1",
  },
  {
    flagName: "🇺🇾",
    countryName: "Uruguay",
    countryWithFlag: "🇺🇾 Uruguay",
    shortCode: "UY (+598)",
    countryWithCode: "Uruguay (+598)",
    value: "+598",
  },
  {
    flagName: "🇺��",
    countryName: "Uzbekistan",
    countryWithFlag: "🇺🇿 Uzbekistan",
    shortCode: "UZ (+998)",
    countryWithCode: "Uzbekistan (+998)",
    value: "+998",
  },
  {
    flagName: "🇻��",
    countryName: "Vanuatu",
    countryWithFlag: "🇻🇺 Vanuatu",
    shortCode: "VU (+678)",
    countryWithCode: "Vanuatu (+678)",
    value: "+678",
  },
  {
    flagName: "🇻🇦",
    countryName: "Vatican",
    countryWithFlag: "🇻🇦 Vatican",
    shortCode: "VA (+379)",
    countryWithCode: "Vatican (+379)",
    value: "+379",
  },
  {
    flagName: "🇻��",
    countryName: "Venezuela",
    countryWithFlag: "🇻🇪 Venezuela",
    shortCode: "VE (+58)",
    countryWithCode: "Venezuela (+58)",
    value: "+58",
  },
  {
    flagName: "🇻🇳",
    countryName: "Vietnam",
    countryWithFlag: "🇻🇳 Vietnam",
    shortCode: "VN (+84)",
    countryWithCode: "Vietnam (+84)",
    value: "+84",
  },
  {
    flagName: "🇻🇬",
    countryName: "British Virgin Islands",
    countryWithFlag: "🇻🇬 British Virgin Islands",
    shortCode: "VG (+1-284)",
    countryWithCode: "British Virgin Islands (+1-284)",
    value: "+1-284",
  },
  {
    flagName: "🇻🇮",
    countryName: "U.S. Virgin Islands",
    countryWithFlag: "🇻🇮 U.S. Virgin Islands",
    shortCode: "VI (+1-340)",
    countryWithCode: "U.S. Virgin Islands (+1-340)",
    value: "+1-340",
  },
  {
    flagName: "🇼🇫",
    countryName: "Wallis and Futuna",
    countryWithFlag: "🇼🇫 Wallis and Futuna",
    shortCode: "WF (+681)",
    countryWithCode: "Wallis and Futuna (+681)",
    value: "+681",
  },
  {
    flagName: "🇪🇭",
    countryName: "Western Sahara",
    countryWithFlag: "🇪🇭 Western Sahara",
    shortCode: "EH (+212)",
    countryWithCode: "Western Sahara (+212)",
    value: "+212",
  },
  {
    flagName: "🇾🇪",
    countryName: "Yemen",
    countryWithFlag: "🇾🇪 Yemen",
    shortCode: "YE (+967)",
    countryWithCode: "Yemen (+967)",
    value: "+967",
  },
  {
    flagName: "🇿��",
    countryName: "Zambia",
    countryWithFlag: "🇿🇲 Zambia",
    shortCode: "ZM (+260)",
    countryWithCode: "Zambia (+260)",
    value: "+260",
  },
  {
    flagName: "🇿🇼",
    countryName: "Zimbabwe",
    countryWithFlag: "🇿🇼 Zimbabwe",
    shortCode: "ZW (+263)",
    countryWithCode: "Zimbabwe (+263)",
    value: "+263",
  },
];

export default countryOptions;
