import {
  VaseIcon,
  ParthenonIcon,
  ColosseumIcon,
  ColumnIcon,
  RunnerIcon,
  DiscusIcon,
} from "@/components/common/Icons";

export const TOTAL_STEPS = 9;

export const stepConfig = [
  {
    stepNumber: 1,
    title: "training_setup.injury.title",
    emoji: "🩹",
    field: "hasInjury",
    options: [
      {
        value: "no",
        emoji: "✅",
        title: "training_setup.injury.options.no_injuries",
        description: "training_setup.injury.options.no_injuries_desc",
        icon: <RunnerIcon className="w-12 h-12" />,
      },
      {
        value: "past",
        emoji: "🕒",
        title: "training_setup.injury.options.past_injury",
        description: "training_setup.injury.options.past_injury_desc",
        icon: <DiscusIcon className="w-12 h-12" />,
      },
      {
        value: "current",
        emoji: "🤕",
        title: "training_setup.injury.options.current_injury",
        description: "training_setup.injury.options.current_injury_desc",
        icon: <VaseIcon className="w-12 h-12" />,
      },
      {
        value: "chronic",
        emoji: "⚠️",
        title: "training_setup.injury.options.chronic_injury",
        description: "training_setup.injury.options.chronic_injury_desc",
        icon: <ColumnIcon className="w-12 h-12" />,
      },
    ],
  },
  {
    stepNumber: 2,
    title: "training_setup.injury.select_locations",
    emoji: "🦴",
    field: "injuryLocations",
    isInjuryLocationStep: true,
    dependsOn: {
      field: "hasInjury",
      values: ["past", "current", "chronic"],
    },
  },
  {
    stepNumber: 3,
    title: "training_setup.injury.rehabilitation",
    emoji: "🏥",
    field: "wantsRehabilitation",
    dependsOn: {
      field: "hasInjury",
      values: ["past", "current", "chronic"],
    },
    options: [
      {
        value: "yes",
        emoji: "🧠",
        title: "training_setup.injury.options.yes_rehab",
        description: "training_setup.injury.options.yes_rehab_desc",
        icon: <ParthenonIcon className="w-12 h-12" />,
      },
      {
        value: "no",
        emoji: "💪",
        title: "training_setup.injury.options.no_rehab",
        description: "training_setup.injury.options.no_rehab_desc",
        icon: <ColumnIcon className="w-12 h-12" />,
      },
    ],
  },
  {
    stepNumber: 4,
    title: "training_setup.environment.title",
    emoji: "🌍",
    field: "environment",
    options: [
      {
        value: "gym",
        emoji: "🏋️",
        title: "training_setup.environment.options.gym",
        description: "training_setup.environment.options.gym_desc",
        icon: <ParthenonIcon className="w-12 h-12" />,
      },
      {
        value: "outside",
        emoji: "🌳",
        title: "training_setup.environment.options.outside",
        description: "training_setup.environment.options.outside_desc",
        icon: <ColosseumIcon className="w-12 h-12" />,
      },
    ],
  },
  {
    stepNumber: 5,
    title: "training_setup.equipment.title",
    emoji: "🛠️",
    field: "equipment",
    options: [
      {
        value: "with_equipment",
        emoji: "🏋️‍♂️",
        title: "training_setup.equipment.options.with_equipment",
        description: "training_setup.equipment.options.with_equipment_desc",
        icon: <ColumnIcon className="w-12 h-12" />,
      },
      {
        value: "no_equipment",
        emoji: "🧘",
        title: "training_setup.equipment.options.no_equipment",
        description: "training_setup.equipment.options.no_equipment_desc",
        icon: <VaseIcon className="w-12 h-12" />,
      },
    ],
  },
  {
    stepNumber: 6,
    title: "training_setup.experience.title",
    emoji: "⏱️",
    field: "experience",
    options: [
      {
        value: "beginner",
        emoji: "🌱",
        title: "training_setup.experience.options.beginner",
        description: "training_setup.experience.options.beginner_desc",
        icon: <RunnerIcon className="w-12 h-12" />,
      },
      {
        value: "intermediate",
        emoji: "🔄",
        title: "training_setup.experience.options.intermediate",
        description: "training_setup.experience.options.intermediate_desc",
        icon: <DiscusIcon className="w-12 h-12" />,
      },
      {
        value: "advanced",
        emoji: "💪",
        title: "training_setup.experience.options.advanced",
        description: "training_setup.experience.options.advanced_desc",
        icon: <ParthenonIcon className="w-12 h-12" />,
      },
      {
        value: "expert",
        emoji: "🏆",
        title: "training_setup.experience.options.expert",
        description: "training_setup.experience.options.expert_desc",
        icon: <ColosseumIcon className="w-12 h-12" />,
      },
    ],
  },
  {
    stepNumber: 7,
    title: "training_setup.goal.title",
    emoji: "🎯",
    field: "goal",
    options: [
      {
        value: "strength",
        emoji: "💪",
        title: "training_setup.goal.options.strength",
        description: "training_setup.goal.options.strength_desc",
        icon: <ColumnIcon className="w-12 h-12" />,
      },
      {
        value: "muscle",
        emoji: "🏋️‍♀️",
        title: "training_setup.goal.options.muscle",
        description: "training_setup.goal.options.muscle_desc",
        icon: <VaseIcon className="w-12 h-12" />,
      },
      {
        value: "lose_weight",
        emoji: "🔥",
        title: "training_setup.goal.options.lose_weight",
        description: "training_setup.goal.options.lose_weight_desc",
        icon: <RunnerIcon className="w-12 h-12" />,
      },
      {
        value: "endurance",
        emoji: "🏃",
        title: "training_setup.goal.options.endurance",
        description: "training_setup.goal.options.endurance_desc",
        icon: <DiscusIcon className="w-12 h-12" />,
      },
    ],
  },
  {
    stepNumber: 8,
    title: "training_setup.frequency.title",
    emoji: "📅",
    field: "frequency",
    isFrequencyStep: true,
  },
  {
    stepNumber: 9,
    title: "training_setup.measurements.title",
    emoji: "📏",
    field: "measurements",
    isMeasurementsStep: true,
  },
];
