
export const TOTAL_STEPS = 9;

export const stepConfig = [
  {
    stepNumber: 1,
    title: "training_setup.injury.title",
    emoji: "🩹",
    field: "hasInjury",
    icon: "mdi:bandage",
    options: [
      {
        value: "no",
        emoji: "✅",
        title: "training_setup.injury.options.no_injuries",
        description: "training_setup.injury.options.no_injuries_desc",
        iconName: "mdi:run-fast",
      },
      {
        value: "past",
        emoji: "🕒",
        title: "training_setup.injury.options.past_injury",
        description: "training_setup.injury.options.past_injury_desc",
        iconName: "mdi:history",
      },
      {
        value: "current",
        emoji: "🤕",
        title: "training_setup.injury.options.current_injury",
        description: "training_setup.injury.options.current_injury_desc",
        iconName: "mdi:medical-bag",
      },
      {
        value: "chronic",
        emoji: "⚠️",
        title: "training_setup.injury.options.chronic_injury",
        description: "training_setup.injury.options.chronic_injury_desc",
        iconName: "mdi:alert-circle-outline",
      },
    ],
  },
  {
    stepNumber: 2,
    title: "training_setup.injury.select_locations",
    emoji: "🦴",
    field: "injuryLocations",
    icon: "mdi:human-male",
    isInjuryLocationStep: true,
    dependsOn: {
      field: "hasInjury",
      values: ["past", "current", "chronic"],
    },
  },
  {
    stepNumber: 3,
    title: "training_setup.injury.rehabilitation",
    emoji: "🏥",
    field: "wantsRehabilitation",
    icon: "mdi:hospital-building",
    dependsOn: {
      field: "hasInjury",
      values: ["past", "current", "chronic"],
    },
    options: [
      {
        value: "yes",
        emoji: "🧠",
        title: "training_setup.injury.options.yes_rehab",
        description: "training_setup.injury.options.yes_rehab_desc",
        iconName: "mdi:brain",
      },
      {
        value: "no",
        emoji: "💪",
        title: "training_setup.injury.options.no_rehab",
        description: "training_setup.injury.options.no_rehab_desc",
        iconName: "mdi:arm-flex",
      },
    ],
  },
  {
    stepNumber: 4,
    title: "training_setup.environment.title",
    emoji: "🌍",
    field: "environment",
    icon: "mdi:earth",
    options: [
      {
        value: "gym",
        emoji: "🏋️",
        title: "training_setup.environment.options.gym",
        description: "training_setup.environment.options.gym_desc",
        iconName: "mdi:dumbbell",
      },
      {
        value: "outside",
        emoji: "🌳",
        title: "training_setup.environment.options.outside",
        description: "training_setup.environment.options.outside_desc",
        iconName: "mdi:tree",
      },
    ],
  },
  {
    stepNumber: 5,
    title: "training_setup.equipment.title",
    emoji: "🛠️",
    field: "equipment",
    icon: "mdi:tools",
    options: [
      {
        value: "with_equipment",
        emoji: "🏋️‍♂️",
        title: "training_setup.equipment.options.with_equipment",
        description: "training_setup.equipment.options.with_equipment_desc",
        iconName: "mdi:weight-lifter",
      },
      {
        value: "no_equipment",
        emoji: "🧘",
        title: "training_setup.equipment.options.no_equipment",
        description: "training_setup.equipment.options.no_equipment_desc",
        iconName: "mdi:meditation",
      },
    ],
  },
  {
    stepNumber: 6,
    title: "training_setup.experience.title",
    emoji: "⏱️",
    field: "experience",
    icon: "mdi:clock-time-eight",
    options: [
      {
        value: "beginner",
        emoji: "🌱",
        title: "training_setup.experience.options.beginner",
        description: "training_setup.experience.options.beginner_desc",
        iconName: "mdi:sprout",
      },
      {
        value: "intermediate",
        emoji: "🔄",
        title: "training_setup.experience.options.intermediate",
        description: "training_setup.experience.options.intermediate_desc",
        iconName: "mdi:refresh",
      },
      {
        value: "advanced",
        emoji: "💪",
        title: "training_setup.experience.options.advanced",
        description: "training_setup.experience.options.advanced_desc",
        iconName: "mdi:arm-flex",
      },
      {
        value: "expert",
        emoji: "🏆",
        title: "training_setup.experience.options.expert",
        description: "training_setup.experience.options.expert_desc",
        iconName: "mdi:trophy",
      },
    ],
  },
  {
    stepNumber: 7,
    title: "training_setup.goal.title",
    emoji: "🎯",
    field: "goal",
    icon: "mdi:target",
    options: [
      {
        value: "strength",
        emoji: "💪",
        title: "training_setup.goal.options.strength",
        description: "training_setup.goal.options.strength_desc",
        iconName: "mdi:weight",
      },
      {
        value: "muscle",
        emoji: "🏋️‍♀️",
        title: "training_setup.goal.options.muscle",
        description: "training_setup.goal.options.muscle_desc",
        iconName: "mdi:human-handsup",
      },
      {
        value: "lose_weight",
        emoji: "🔥",
        title: "training_setup.goal.options.lose_weight",
        description: "training_setup.goal.options.lose_weight_desc",
        iconName: "mdi:fire",
      },
      {
        value: "endurance",
        emoji: "🏃",
        title: "training_setup.goal.options.endurance",
        description: "training_setup.goal.options.endurance_desc",
        iconName: "mdi:run-fast",
      },
    ],
  },
  {
    stepNumber: 8,
    title: "training_setup.frequency.title",
    emoji: "📅",
    field: "frequency",
    icon: "mdi:calendar",
    isFrequencyStep: true,
  },
  {
    stepNumber: 9,
    title: "training_setup.measurements.title",
    emoji: "📏",
    field: "measurements",
    icon: "mdi:ruler",
    isMeasurementsStep: true,
  },
];
